### ISSUE TITLE
[BottomSheet] How to apply border radius to bottom sheet container

### ISSUE THREAD

**Issue by mrcretu** [Akylas/nativescript-material-components#102]
Hello, I'm using the bottom sheet in a nativescript angular application. The only thing that I can't/ I don't know is to style the main container inside which my injected component took place.
More exactly I want to set a border-radius for it and after some research I came with this issue.
![Screenshot 2020-01-22 at 12 33 45](https://user-images.githubusercontent.com/35378001/72887043-96173e00-3d13-11ea-8d6b-ec36c27aa12f.png)
I've uploaded a screensshot to understand better what I'm trying to accomplish.

Thanks in advance.

**Comment by farfromrefug** [comment]
@mrcretu published a new version. Add `transparent:true` to your bottomsheet options

**Comment by mrcretu** [comment]
Thank you very much, it's working perfectly.
