### ISSUE TITLE
TextField Android: focus, blur, textChange and returnPress events not triggered (working correctly on iOS)

### ISSUE THREAD

**Issue by felixkrautschuk** [Akylas/nativescript-material-components#104]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

On Android, the events for focus, blur, textChange and returnPress are not triggered at all. On iOS, the events are working as expected.

Here is what I'm doing:

XML:
```
<mdt:TextField id="textField1" 
    focus="onFocus" 
    blur="onBlur" 
    textChange="onTextChange" 
    returnPress="onReturnPress"
    variant="outline"/>
```

TS:
```
export function onTextChange(args: EventData) {
    let textField = args.object as TextField;
    console.log(textField.id + " has changed text...");
}

export function onFocus(args: EventData) {
    let textField = args.object as TextField;
    console.log(textField.id + " has got focus...");
}

export function onBlur(args: EventData) {
    let textField = args.object as TextField;
    console.log(textField.id + " has lost focus...");
}

export function onReturnPress(args: EventData) {
    let textField = args.object as TextField;
    console.log(textField.id + " returnPress...");
}
```

### Which platform(s) does your issue occur on?
- Android
- tested on Emulators with Android 7.1.1 and 10
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.3.3
- Cross-platform modules: @nativescript/core 6.3.2
- Runtime(s): tns-android 6.3.1
- Plugin(s): nativescript-material-textfield 3.1.3

### Please, tell us how to recreate the issue in as much detail as possible. 
Open the sample app provided below, focus/unfocus the textfields and change the text of some fields. You will see some output in the console on iOS, but not on Android (except for the default NS TextField that I added to the page to figure out if it is a problem of the plugin or of NS for Android in general)

### Is there any code involved? 
[nativescript-materialtextfield.zip](https://github.com/Akylas/nativescript-material-components/files/4127625/nativescript-materialtextfield.zip)

**Comment by farfromrefug** [comment]
@felixkrautschuk version 3.1.4 should fix the issue. Can you please close that issue if fixed?
