### ISSUE TITLE
TextField Android: keyboardType is ignored (working on iOS)

### ISSUE THREAD

**Issue by felixkrautschuk** [Akylas/nativescript-material-components#105]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

On Android, setting the keyboard type (e.g. to number or phone) has no effect, while it is working as expected on iOS.

```
<mdt:TextField id="textField1" keyboardType="phone" hint="Material TextField"/>
```

Android:

![Bildschirmfoto 2020-01-29 um 12 18 22](https://user-images.githubusercontent.com/6443021/73352676-ee10f000-4291-11ea-882b-2478bc6020bf.png)

iOS:
![Bildschirmfoto 2020-01-29 um 12 19 46](https://user-images.githubusercontent.com/6443021/73352697-f701c180-4291-11ea-9eeb-da49133ad63a.png)

### Which platform(s) does your issue occur on?
- Android
- tested on Emulators with Android 7.1.1 and 10
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.3.3
- Cross-platform modules: @nativescript/core 6.3.2
- Runtime(s): tns-android 6.3.1
- Plugin(s): nativescript-material-textfield 3.1.3

### Please, tell us how to recreate the issue in as much detail as possible. 
Open the sample app provided below, tap on the MaterialTextField and you will see the default Android keyboard, not configured for "Phone".

### Is there any code involved? 
[nativescript-materialtextfield.zip](https://github.com/Akylas/nativescript-material-components/files/4127674/nativescript-materialtextfield.zip)

**Comment by farfromrefug** [comment]
@felixkrautschuk version 3.1.4 should fix the issue. Can you please close that issue if fixed?
