### ISSUE TITLE
TextField Android adds new lines when return-Button is pressed (not happening on iOS)

### ISSUE THREAD

**Issue by felixkrautschuk** [Akylas/nativescript-material-components#106]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

On Android, the TextField acts more lika a TextView, because pressing the return-Button of the keyboard adds new lines to the field. 

![Bildschirmfoto 2020-01-29 um 12 36 12](https://user-images.githubusercontent.com/6443021/73353838-96c04f00-4294-11ea-8649-c3ed56fa1be2.png)

I have not found any way to prevent adding new lines. Setting the [returnKeyType](https://docs.nativescript.org/api-reference/classes/_ui_text_field_.textfield#returnkeytype) to "next" or "send" has no effect on Android side.
On iOS, pressing the return-Button causes the TextField to loose focus (which is the expected behaviour for a simple TextField).

### Which platform(s) does your issue occur on?
- Android
- tested on Emulators with Android 7.1.1 and 10
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.3.3
- Cross-platform modules: @nativescript/core 6.3.2
- Runtime(s): tns-android 6.3.1
- Plugin(s): nativescript-material-textfield 3.1.3

### Please, tell us how to recreate the issue in as much detail as possible. 
Open the sample app provided below, tap on the MaterialTextField and press the keyboard's return button.

### Is there any code involved? 
[nativescript-materialtextfield.zip](https://github.com/Akylas/nativescript-material-components/files/4127720/nativescript-materialtextfield.zip)

**Comment by lostation** [comment]
Re,

Same here.... following last update to 3.1.3
-> MDtextfield become auto multiline on enter 
-> Also secure="true" field doesn't work at all... 
-> textChange event not fired anymore etc ... 

--->  Revert to 2.5.4 makes things work again...

**Comment by farfromrefug** [comment]
Just saw that. Something changed... Need to fix it

**Comment by lostation** [comment]
Anyway while waiting for a version fix.
I just wanted to thank you for your great work!

Lo 

Le 29 janv. 2020 16:37, à 16:37, Martin Guillon <notifications@github.com> a écrit:

**Comment by farfromrefug** [comment]
@lostation thanks! That a big issue happening here and a lot of other side effects.
Right now i am fighting to find out where it comes from. Can t even find a way to rollback to a working version :s

**Comment by lostation** [comment]
As I already mentionned, I spent my day to find that the 2.5.4 was re-working well.

I changed all the nativescript-material-* to 2.5.4.

"nativescript-angular": "~8.20.4",
"nativescript-material-button": ".5.4",
"nativescript-material-cardview": "2.5.4",
"nativescript-material-ripple": "2.5.4",
"nativescript-material-textfield": "2.5.4",

tns —version    6.3.3

Lo.

**Comment by farfromrefug** [comment]
@lostation indeed! new version is here!
@felixkrautschuk version 3.1.4 should fix the issue. Can you please close that issue if fixed?

**Comment by lostation** [comment]
Just tried the new 3.1.4 and it works ! Well done !!! ;)

**Comment by lostation** [comment]
@felixkrautschuk Can you test it ?

**Comment by johandrott** [comment]
I experienced the same problem and tried to upgrade to nativescript-material-textfield 3.1.4 but it did not work. Only after upgrading nativescript-material-button to the same version 3.1.4 did the textfield start to work as expected. Does nativescript-material-textfield depend on nativescript-material-button?

**Comment by farfromrefug** [comment]
The issue is with a dep that th all have: nativescript-material-core. Thanks to npm and the way it works you needed to update both

**Comment by felixkrautschuk** [comment]
@farfromrefug Thank you for the very fast fixes! :-) (of all issues I created yesterday)

**Comment by lostation** [comment]
@farfromrefug <https://github.com/farfromrefug> you rock !!!
