### ISSUE TITLE
TextField Android: data-binding to text-property not working (iOS is working)

### ISSUE THREAD

**Issue by felixkrautschuk** [Akylas/nativescript-material-components#107]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

On Android, the databinding for the text-Property of Materdial TextField does not work at all, while it works as expected on iOS.

XML:
```
<mdt:TextField text="{{ myText }}" hint="My hint"/>
```

TS:
```
import {fromObject} from "@nativescript/core/data/observable";

export let vmMain = fromObject({
    myText: "Test"
});
```

### Which platform(s) does your issue occur on?
- Android
- tested on Emulators with Android 7.1.1 and 10
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.3.3
- Cross-platform modules: @nativescript/core 6.3.2
- Runtime(s): tns-android 6.3.1
- Plugin(s): nativescript-material-textfield 3.1.3

### Please, tell us how to recreate the issue in as much detail as possible. 
Open the sample app provided below, type something to the textfield and you should see the changed text in the ActionBar's title. But this is only working on iOS. On Android, when you tap into the textfield, the text in the ActionBar's title disappears and it never changes while typing to the textfield.

### Is there any code involved? 
[nativescript-materialtextfield.zip](https://github.com/Akylas/nativescript-material-components/files/4127840/nativescript-materialtextfield.zip)

**Comment by farfromrefug** [comment]
@felixkrautschuk version 3.1.4 should fix the issue. Can you please close that issue if fixed?
