### ISSUE TITLE
MDRipple only work inside stack-layout on android

### ISSUE THREAD

**Issue by hoatructhanhlam** [Akylas/nativescript-material-components#11]
As the title, I working Nativescript-Vue 5.2.2
If I wrap MDRipple inside GridLayout tag, it won't work, but in IOS it works fine

**Comment by farfromrefug** [comment]
@hoatructhanhlam i think it is not related to GridLayout. But more to tap events.
Right now the ripple should only work if the view has tap event.
I can fix it but it would create another issue, itemtap(listview) would not be triggered from within a ripple...

Need to find a correct fix.

let me know if the tap trick works
