### ISSUE TITLE
dropdown-menu

### ISSUE THREAD

**Issue by bornes** [Akylas/nativescript-material-components#111]
Hi,
The project has some kind of roadmap? Have you planned the development of dropdown menus?

Thanks 🤜🤛

**Comment by farfromrefug** [comment]
No roadmap. And nothing planned yet. But PRs are welcome!

**Comment by Logikgate** [comment]
I would love to have this as well and would be willing to work on it.  Unfortunately there isn't a material design iOS version of a dropdown menu yet so I guess we will just need to wait until there is one

https://github.com/material-components/material-components-ios/tree/develop/components/Menus

**Comment by farfromrefug** [comment]
@Logikgate actually interested in this too.
However for the reason you exlained what i do is:
* android: dropdown menu (not implemented yet)
* ios: i use a bottomsheet as an action sheet.

I looks pretty good and seems pretty fluent to the user (which is not used to dropdown menus on iOS anyway)
