### ISSUE TITLE
Material TextField returnKeyType Not openning the Field

### ISSUE THREAD

**Issue by juanbonoso** [Akylas/nativescript-material-components#112]
### Which platform(s) does your issue occur on?
iOS/Android/Both
Physical devices: 
Android 9 Pie, and on iphone 8 (ios13)

### Please, provide the following version numbers that your issue occurs with:
**I am using nativescript-vue**
CLI: 6.3.3
Cross-platform modules: 6.3.2
Runtime(s):
tns-ios: 6.5.0-2020-01-29-131939-02
tns-android: 6.4.0-2020-01-31-144644-03
- Plugin(s): 
```
"dependencies": {
		"nativescript-material-cardview": "^3.1.5",
		"nativescript-material-snackbar": "^3.1.5",
		"nativescript-material-textfield": "^3.1.5",
}
```
### Please, tell us how to recreate the issue in as much detail as possible. 
**Open a MaterialTextfield**
### ANDROID
![dump_7504824868784100857](https://user-images.githubusercontent.com/43289624/74161080-652c7980-4bec-11ea-9f67-0c667fd8dc45.png)
**Click On Next: (It Just select the next textfield, but does not open with the keyboard which is really annoying)**
![dump_7643754346291253756](https://user-images.githubusercontent.com/43289624/74161239-a02ead00-4bec-11ea-85a1-63e560d0d71e.png)
### iOS
`returnKeyType="next"` Is not working. Nothing happens when you click on next.
### Is there any code involved? 
```
<MDTextField
returnKeyType="next"
v-model="signUpForm.firstname"
/>
<MDTextField
returnKeyType="next"
v-model="signUpForm.lastname"
/>
```

**Comment by kryoware** [comment]
@juanbonoso this might be a hack but I think you can try this (this should theoretically work with Android)

MDTextField is a layout that contains the actual textfield. The layout is what's getting focused when you tap enter. The code below will react to the initial focus and will focus on to the textfield inside. 

Template:
```
<MDTextField
  @focus="onFocus"
  ...
/>
```

Script:
```
methods: {
  ...
  onFocus(args) {
    const inputLayout = args.object

    if (platform.isAndroid) {
      inputLayout.android.getEditText().requestFocus()
    }
  }
}
```

**Comment by juanbonoso** [comment]
I just try the code but does not work :/

**Comment by farfromrefug** [comment]
Might look at this is the future. I already fixed that issue in another framework so should be fairly easy.
Though no time right now :s

**Comment by juanbonoso** [comment]
@farfromrefug is there a way to contribute with the project?

**Comment by PabloPG** [comment]
@juanbonoso try this:

```
<MDTextField
    #nombres
    (returnPress)="apelidos.requestFocus()"
></MDTextField>

<MDTextField
    #apelidos 
    (returnPress)="contrasenha.requestFocus()">
</MDTextField>
```

**Comment by alexist** [comment]
You not always know the next input to focus. For example, i have create a wrapper component AppTextFieldComponent app-text-field.
```
<StackLayout [formGroup]="parentForm" class="input-field">
    <MDTextField ...
</StackLayout>
```

Other components use this component  :
```

<app-text-field [parentForm]="form"                   
                        formControlName="email"
                        hint="Email"></app-text-field>
<app-text-field [parentForm]="form"                   
                        formControlName="phone"
                        hint="Phone"></app-text-field>
```
I m looking for a solution more generic, like this one https://github.com/Akylas/nativescript-material-components/issues/112#issuecomment-584213635 (not working)
