### ISSUE TITLE
[Feature] Circular Loading Indicator In Buttons

### ISSUE THREAD

**Issue by Logikgate** [Akylas/nativescript-material-components#113]
Would you be open to a pull request that adds a loading prop to MDButton to allow the display of a circular loading indicator?

**Material Design Reference**
Reference the Placement section where it recommends using circular-progress-indicators for buttons
https://material.io/components/progress-indicators/#circular-progress-indicators

**Comment by farfromrefug** [comment]
@Logikgate You mean a loading indicator inside the button?
Is this implemented natively?
If so yes for a property. If no i think a new component would be better

**Comment by Logikgate** [comment]
Yep a loading indicator in the button

It doesn't look like com.google.android.material.button.MaterialButton nor MDCButton implement it natively but it is recommended by the material spec to do this for long running tasks.

On iOS we could use MDCActivityIndicator and on Android it appears there isn't a google created progress bar that conforms to the material spec so I would probably end up using this: https://github.com/zhanghai/MaterialProgressBar

Most of the implementations of this I see just use a loading prop which triggers the text to be replaced with a loading indicator. Do you think a new component should be introduced to add this functionality? Something like MDButtonLoading? It seems a little overkill since they will both be inheriting from the same base classes just one will have more functionality than the other

![Feb-12-2020 11-22-43](https://user-images.githubusercontent.com/2379994/74354915-10bf0080-4d8a-11ea-8076-b5f82bd4a340.gif)

**Comment by farfromrefug** [comment]
@Logikgate Ok i see. So yes i think it needs to be a new component subclassing MDButton. Why: 
* i am currently fighting for perms in {N}. Keeping things "light" is the key. And most users will use a button without this so it should be "separated".
* it uses a lib outside of material official components. Which i try to avoid (for now).

So it would be best to create a totally new {N} plugin which depends on `nativescript-material-button`.
I can help you if you want

**Comment by Logikgate** [comment]
Ah yeah ok I understand. Yeah let's do it!  Would you like to stub a new plugin into the repo named how you want and then I can take it from there?

**Comment by farfromrefug** [comment]
@Logikgate we can actually handle it here is this mono repo. Might be a good idea.
So:
* fork
* create a new folder inside `packages` with the package name you want. Maybe `nativescript-material-loadingbutton` ? Not sure, if you have something better go for it.
* That s where you ll put the Podfile ...
* create a new folder in src like `loadingbutton` and start implementing.
* dont forget in the `tsconfig.json` in your new package folder to point to your src folder.

Let me know how it goes
