### ISSUE TITLE
iOS TextField & TextView Stroke Color Only Affects Active Fields

### ISSUE THREAD

**Issue by Logikgate** [Akylas/nativescript-material-components#114]
On android setting stroke-color affects the stroke of TextFields and TextViews regardless of whether or not the field is active.

On iOS setting stroke-color only affects the stroke of active fields.

I believe the android functionality is the desired functionality. If you agree I will make a pull request, all that needs to be done is for normalColor to also be set in these two methods.

https://github.com/Akylas/nativescript-material-components/blob/679da4fddc00ad695679a8119cab2d68674dbd32/src/textfield/textfield.ios.ts#L189-L192

https://github.com/Akylas/nativescript-material-components/blob/679da4fddc00ad695679a8119cab2d68674dbd32/src/textview/textview.ios.ts#L248-L251

**Comment by farfromrefug** [comment]
@Logikgate i actually dont see that behavior on android!
![Screenshot_1582029721](https://user-images.githubusercontent.com/655344/74737135-83c9ea80-5254-11ea-8f7a-43b4900d7e51.png)
![Screenshot_1582029723](https://user-images.githubusercontent.com/655344/74737136-84fb1780-5254-11ea-86a7-1b4edab0dc74.png)

Might be an issue with your android material lib version?

**Comment by Logikgate** [comment]
Hmm you're right, I just updated and don't see that behavior anymore. Sorry about that!

This does bring up a different question though. Is there a way to style the non-active border and floating placeholder color? If not would you be open to me adding a properties to do so?

I'm running into a problem when implementing dark mode since the non-active border is always dark. What I'm looking to achieve is this:

Light Mode (existing behavior)
![Screen Shot 2020-02-18 at 8 19 16 AM](https://user-images.githubusercontent.com/2379994/74739742-8235fd80-5227-11ea-9793-356eb150bbf6.png)

Dark Mode (non-active stroke and non-active placeholder color to be white)
![Screen Shot 2020-02-18 at 8 19 29 AM](https://user-images.githubusercontent.com/2379994/74739749-8530ee00-5227-11ea-974e-3a98019ffaa6.png)

I would propose to add two new properties to control the non-active stroke and placeholder colors. strokeDefaultColor and floatingDefaultColor (or some other names).  This would allow NS users to use css to set these which works nicely with NS's .ns-dark class that is added automatically to the root of pages in dark mode.
```
.ns-dark MDTextField {
    strokeDefaultColor: #fafafa;
    floatingDefaultColor: #fafafa;
}
```

**Comment by farfromrefug** [comment]
Yes we can maybe use inactive in the name would be better.
BTW shouldn't that be already implemented android? I mean did you try to use `setDefaultNightMode` ?

**Comment by Logikgate** [comment]
Yeah that does work on Android but since there is no analog to that on iOS (that I know of) being able to set the properties via css will cover that case.

Also, it looks like prior to 1.2.0-alpha04 it isn't possible, at runtime, to change the inactive stroke color of TextLayoutView.  In 1.2.0-alpha04 they added a setBoxStrokeColorStateList which allows us to specify different colors for different states.

I imagine you don't want to rely on an alpha version so I will make the pull request work with 1.1.0 by detecting if setBoxStrokeColorStateList is available or not and doing nothing on android if it isn't.  Then when 1.2.0 stable comes out everything will just work.

**Comment by farfromrefug** [comment]
Ok i am not opposed to it. It can be useful. Now another thing which bugs me is that it should work on ios too. Will have to check that

**Comment by Logikgate** [comment]
Alright, just updated the pull request #115

iOS works and Android works if you target 1.2.0-alpha04

**Comment by farfromrefug** [comment]
@Logikgate thanks for the PR will look.
For me it works with `1.2.0-alpha01`.
I have not made the switch to `1.2.0-alpha04` as it had issues for me.

**Comment by NavruzbekNoraliev** [comment]
> Alright, just updated the pull request #115
> 
> iOS works and Android works if you target 1.2.0-alpha04

I think this bug is not solved yet, i use    "@nativescript-community/ui-material-textfield": "^5.2.1",  also in ios.scss i use 

```
.mat-input {
  stroke-color: $dark-green;
  width: 100%;
  stroke-inactive-color: $dark-green;
  floating-color: black;
  floating-inactive-color: black;
  .ns-dark & {
    floating-color: white;
    floating-inactive-color: white;
  }
}
```

**Comment by farfromrefug** [comment]
@NavruzbekNoraliev saying `"^5.2.1"` wont give any indication. And again you dont give enough info.
Your "code" wont help and you dont even say what your issue actually is or what you see.

**Comment by NavruzbekNoraliev** [comment]
<img width="325" alt="Screenshot 2021-04-12 at 15 08 51" src="https://user-images.githubusercontent.com/44977644/114378283-fefd0700-9ba0-11eb-8270-21135bcc4a52.png">
I seee this, look at the second field you see when its inactive its black, but the theme is dark, so i want it to be white with the help of css

**Comment by farfromrefug** [comment]
@NavruzbekNoraliev and it works in white theme? works if you put blue instead of black? 
I am thinking this is theme related

**Comment by NavruzbekNoraliev** [comment]
no, i want to make hint to be white, but it doesn't being set even, blue did not work as well

**Comment by farfromrefug** [comment]
@NavruzbekNoraliev without the theme ? You were talking about dark theme. I want to know if it works correctly WITHOUT dark theme

**Comment by NavruzbekNoraliev** [comment]
as i said no, it doesn't work in light theme nor without dark as well, or do you want to trow a blame to dark theme as usual😏

**Comment by farfromrefug** [comment]
@NavruzbekNoraliev really and you expect help with such behavior ? good luck ...

**Comment by NavruzbekNoraliev** [comment]
as usual ... 
next time try to learn more about what you do, and only then hurry to help someone

**Comment by rigor789** [comment]
@NavruzbekNoraliev Please keep issues free of snarky remarks. When maintainers ask you questions, it's not to avoid helping, but to better understand the issue & gain more context. In fact, all the questions are to help **you**, and not the other way around, we want to help, but if you make it difficult, we may just give up and move on.

**Comment by NavruzbekNoraliev** [comment]
@rigor789 ok
