### ISSUE TITLE
[MDCardView - iOS]  Button inside card does not trigger tap

### ISSUE THREAD

**Issue by mrcretu** [Akylas/nativescript-material-components#117]
Hello, I'm using Material Card view and I faced an issue related a button inside a card view. The problem is when I try to press the button inside card, the action is seen as a card tap not a button tap.

The issue is present only on iOS, on Android it's working as expected.

Maybe it's something I do wrong, and I need some help. Thanks in advance

**Comment by farfromrefug** [comment]
@mrcretu strange never seen that behavior. Might be an issue on the native lib side.
Can you share versions and a very simple sample project?
THanks

**Comment by mrcretu** [comment]
[https://www.dropbox.com/s/hrj4a53ni1cpo5k/Screen%20Recording%202020-02-26%20at%2012.02.59.mov?dl=0](url)

I've made a video that can show you the problem.

### Which platform(s) does your issue occur on?
- iOS
- iOS 13.3
- emulator
### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.3.3
- "tns-android": {
      "version": "6.3.0"
    },
    "tns-ios": {
      "version": "6.3.0"
    }
- Plugin(s): "nativescript-material-cardview": "^3.1.4"

Hope the video it's enough to figure it out which is the problem, if not I can make a simpla sample project or to paste some code here.

**Comment by farfromrefug** [comment]
@mrcretu sorry a video is not enough. I need a sample project to reproduce here. THanks

**Comment by mrcretu** [comment]
[https://github.com/mrcretu/MDCardView-sample](url)

Here is a sample. I've noticed that if I place a Button inside MDCardView it's working as expected. But if the button is inside another component like: 
<MDCardView>
   <component>
     <Button>
   <component>
<MDCardView>
then the issue is reproduced.
As I said, maybe it's something that I do wrong but I don't know exactly what.
Thanks in advance!

**Comment by farfromrefug** [comment]
Ok so first i thought you were talking about tap events. But you are talking about touch highlight. 

I dont use angular so might be related to angular. You sub component thing might be the source of the issue.
Now it can also be a bug with the native lib.
You can look on their repo [here](https://github.com/material-components/material-components-ios) to see if anyone is facing the issue.

Can't do much more right now
