### ISSUE TITLE
Bottom sheet gap on iphoneX and higher 

### ISSUE THREAD

**Issue by Panimaster** [Akylas/nativescript-material-components#118]
### Which platform(s) does your issue occur on?
- iPhone X and newer 

### Please, provide the following version numbers that your issue occurs with:
- 6.3.0
- Angular: 8.2.14

### Please, tell us how to recreate the issue in as much detail as possible. 
We tried to implement the material bottom sheet in our app. The component works perfectly fine, except for IOS X and newer devices with safe areas. Unfortunately the height of the component cannot be set to auto and most importantly, there is always a gap on the bottom which we cannot remove (see screenshot).

We already tried several bottom sheet options (ignoreBottomSafeArea and so on) with no success.

### Code Sample: 
`
<StackLayout class="create-trip-decider" backgroundColor="white" height="auto" [style.margin-top]="getMarginTop()">

    <FlexboxLayout class="drag-notifier-wrap" justifyContent="center" alignItems="center">
        <StackLayout class="drag-notifier"></StackLayout>
    </FlexboxLayout>

    <Label class="title" text="{{ 'choose_direction' | L }}"></Label>

    <ng-container *ngFor="let modus of createTripModi; let index = index">
        <GridLayout class="modus-entry" (tap)="onDecide(modus)" ripple rows="50" columns="auto,*" width="100%">
            <Image class="modus-image" row="0" column="0" horizontalAlignment="left"
                [src]="'~/images/create-trip/' + modus?.image" width="30"></Image>
            <Label class="modus-name" row="0" column="1" (loaded)="onLabelLoaded($event)"
                text="{{modus?.name | L}}"></Label>
        </GridLayout>
    </ng-container>
</StackLayout>
`

### result

https://pasteboard.co/IWAGale.png

**Comment by farfromrefug** [comment]
@Panimaster i use it with auto height and bottom safe area working well.
Can you reproduce in a very simple project(please no angular :s ) ?
By doing so i can check if it is a plugin or issue or something higher.
