### ISSUE TITLE
MDSlider Angular bug with Gesture Events

### ISSUE THREAD

**Issue by pkubasiak** [Akylas/nativescript-material-components#12]
In the Angular Slider component, gesture events (pan, touch) breaks the component's operation. I tested Touch and Pan events. The bug occurs even if we place the Slider in StackLayout and listen to the gesture events on it.

### Which platform(s) does your issue occur on?
- iOS
- emulator

### Please, provide the following version numbers that your issue occurs with:
natviescript 5.3.0
tns-core-modules has 5.3.1 
tns-ios has 5.3.1 

plugin version:
 "nativescript-material-slider": "2.2.3",

### Please, tell us how to recreate the issue in as much detail as possible. 
Add listener (touch) or (pan) to MDSlider in angular
  

### Is there any code involved? 
  <MDSlider maxValue="100" value="50" minValue="0" (pan)="onPan($event)"></MDSlider>

    onPan($event) {
     
    }

**Comment by farfromrefug** [comment]
@pkubasiak i am not sure you can use use pan gesture on a MD Slider. You should test with the native version [here](https://github.com/material-components/material-components-ios/tree/develop/components/Slider) to see

**Comment by farfromrefug** [comment]
@pkubasiak i will close this due to inactivity
