### ISSUE TITLE
Fullscreen bottomsheet angular

### ISSUE THREAD

**Issue by jelledijkstra97** [Akylas/nativescript-material-components#121]
Is it possible to let a bottom sheet be fullscreen? If I set the height of the bottom sheet equal to the height of my screen it results in the following:

![Screenshot_20200229-161233_PingCloud POS](https://user-images.githubusercontent.com/44847602/75610111-a68ab780-5b0e-11ea-95e3-9e4631a5be5d.jpg)

Although I am able to scroll the view up I would to have it fullscreen from the start. How can I achieve this?

**Comment by farfromrefug** [comment]
@jelledijkstra97 dont think you can.
