### ISSUE TITLE
TextField hide error icon

### ISSUE THREAD

**Issue by wesoly935** [Akylas/nativescript-material-components#123]
### Which platform(s) does your issue occur on?
- Android

### Please, tell us how to recreate the issue in as much detail as possible. 
I using TextField with validation message via prop: ` :error="error"`

Is any way to hide error icon on right side of TextField?
![image](https://user-images.githubusercontent.com/11411640/75682972-930a5880-5c96-11ea-91f3-b16cd552a1ab.png)

**Comment by farfromrefug** [comment]
@wesoly935 not implemented yet. PR are welcome
