### ISSUE TITLE
Textfield stroke color when without focus

### ISSUE THREAD

**Issue by PabloPG** [Akylas/nativescript-material-components#129]
### Which platform(s) does your issue occur on?
- iOS/Android/Both:      Android
- iOS/Android versions:     API 29
- emulator or device. What type of device?     emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.5
- Cross-platform modules: @nativescript/core@6.5.0
- Runtime(s): 6.5
- Plugin(s):

```
"dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "~2.3.3",
    "nativescript-angular": "~8.21.0",
    "nativescript-material-textfield": "^3.1.15",
    "nativescript-ui-sidedrawer": "~8.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.5.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "codelyzer": "~4.5.0",
    "nativescript-dev-webpack": "~1.5.1",
    "node-sass": "^4.7.1",
    "tns-platform-declarations": "^6.5.0",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3"
  },
```

### Please, tell us how to recreate the issue in as much detail as possible. 
I'm trying to assign a color to the textfield when it has no focus

### Is there any code involved? 
```
<StackLayout class="form">
	<MDTextField
		#usuario
		hint="Usuário"
		variant="outline"
		formControlName="usuario"
		strokeColor="#FFFFFF"
		placeholdercolor="#FFFFFF"
		autocorrect="false"
		[isEnabled]="!loging"
		keyboardType="url"
		returnKeyType="next"
		autocapitalizationType="none"
		marginTop="10"
		(returnPress)="senha.requestFocus()"
		class="user"
	>
	</MDTextField>

	<MDTextField
		#senha
		hint="Senha"
		variant="outline"
		formControlName="senha"
		autocorrect="false"
		strokeColor="#FFFFFF"
		placeholdercolor="#FFFFFF"
		[isEnabled]="!loging"
		keyboardType="email"
		returnKeyType="next"
		autocapitalizationType="none"
		marginTop="10"
		(returnPress)="onLoginTap()"
	>
	</MDTextField>

</StackLayout>
```

![image](https://user-images.githubusercontent.com/5642845/77579146-9620ef00-6eb8-11ea-8f49-d013e16e7183.png)

same with strokeInactiveColor doesn't work

**Comment by lerroux** [comment]
I have the same issue.

**Comment by farfromrefug** [comment]
Not supported yet. PR are welcome

**Comment by diegovincent** [comment]
Does `style: border-color` work @lerroux @PabloPG ?

**Comment by farfromrefug** [comment]
@diegovincent no it wont work. Need to be "handled" in the plugin. PR are welcome ;)

**Comment by diegovincent** [comment]
@farfromrefug I have not gotten experience with Android or iOS, even though I do know a bit of Java, Typescript and have done a tiny modification in ObjC. If you can explain a bit how everything works, I'd love to maintain this repository, this is huge for {N}!

**Comment by farfromrefug** [comment]
@diegovincent i would first advise you to look for Nativescript tutorials on how to write plugins.
Then you would need to look at google material libs for iOS and Android to see the APIs. Then when you have all that, you can look at my plugin code and try to add the new property to handle the border color.
