### ISSUE TITLE
Bottom Navigation inside a lazy loaded module causes HMR to crash on iOS

### ISSUE THREAD

**Issue by kmmccafferty96** [Akylas/nativescript-material-components#134]
### Which platform(s) does your issue occur on?

iPhone 11 Simulator running iOS 13.4
iPhone X running iOS 13.4.1
(works fine on Android)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.5.0
- Cross-platform modules: 6.5.1
- iOS Runtime: 6.5.0
- Plugins:
```
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "~2.3.3",
    "nativescript-angular": "~8.21.0",
    "nativescript-material-bottomnavigationbar": "^3.1.16",
    "nativescript-material-core": "^3.1.16",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.5.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "nativescript-dev-webpack": "~1.5.1",
    "typescript": "~3.5.3"
  },
```

### Please, tell us how to recreate the issue in as much detail as possible. 

If I add the nativescript-material-bottomnavigationbar to a component in a lazy loaded module and hot module replacement is triggered by saving, the app crashes on both the iOS simulator and my device. If I make another change and save that, the app will reload just fine. The steps below might make this more clear:

1. Run `tns run ios` (app loads fine)
2. Make a change and save, causing HMR to happen (app crashes).
3. Make another change and save (app starts again just fine).
4. Make another change and save (app crashes).
5. Make another change and save (app starts again just fine).

So on and so forth.

The only error in the console that I can really pick out is this:
`JavaScript error:
file: node_modules/@nativescript/core/ui/core/view/view.ios.js:47:0: JS ERROR TypeError: nativeView.setNeedsLayout is not a function. (In 'nativeView.setNeedsLayout()', 'nativeView.setNeedsLayout' is undefined)
***** Fatal JavaScript exception - application has been terminated. *****`

Removing the bottom navigation from the component causes the hot module replacement to start working fine again.

I have included the full logs starting from the file change detection [here](https://github.com/Akylas/nativescript-material-components/files/4453778/logs.txt).

### Is there any code involved? 
I created a bare-bones NativeScript app demonstrating this here: [test-app.zip](https://github.com/Akylas/nativescript-material-components/files/4453782/test-app.zip) (removed node_modules and platform folders)

**Comment by farfromrefug** [comment]
Does not seem to be an error here but in N or the webpack or the cli
I would try to post i there.

**Comment by kmmccafferty96** [comment]
Will do. Thanks for your help.

**Comment by kmmccafferty96** [comment]
I noticed that you released nativescript-material-tabs. Can/should I use this instead of nativescript-material-bottomnavigationbar?

**Comment by farfromrefug** [comment]
Nop not the same it is the code from N tabs. It will get removed from there
