### ISSUE TITLE
MDButton Elevation not working on Android.

### ISSUE THREAD

**Issue by juanbonoso** [Akylas/nativescript-material-components#137]
### Which platform(s) does your issue occur on?
- Android Oreo.(May be on other android version)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.5.0
- Cross-platform modules: 6.5.1
- Runtime(s): 
```
"tns-ios": {
			"version": "6.5.0"
		},
"tns-android": {
			"version": "6.5.0"
		}
```
- Plugin(s): 
		"nativescript-material-button": "^3.2.1",
		"nativescript-material-cardview": "^3.2.1",
		"nativescript-material-dialogs": "^3.2.1",
		"nativescript-material-snackbar": "^3.2.1",

### Please, tell us how to recreate the issue in as much detail as possible. 
Install the plugin, use it. 

The problem is that the drop shadow disappears when aplying a **borderRadius** only on android. I am trying to simulate a floating action button to use icon fonts. I have read the samples from vue to create one.

I have tried to change the background of the layouts and the page to see if something happens, but no drop shadow appears. It just looks like a normal circular flat button. I am sure that is the **border radius property, it works as expected without this property.** 

### Is there any code involved? 
**This code represent the first 2 buttons of the image**
```
<StackLayout>
		<MDButton
			class="falseFAb bg-green"
			text="+"
			verticalAlign="center"
			color="blue"
			backgroundColor="white"
			@tap="onTap"
		/>
		<MDButton id="button1" elevation="10" class="falseFAb" text="+"  />
</StackLayout>
```

![Screen Shot 2020-04-14 at 13 19 58](https://user-images.githubusercontent.com/43289624/79259714-c3771200-7e52-11ea-90dd-6a69420819ed.png)

**Open it, on other tab for better picture quality.**

app.css
```
.falseFAb {
    elevation: 2;
    font-size: 40;
    border-radius: 32;
    width: 64;
    height: 64;
}
```

**Comment by farfromrefug** [comment]
@juanbonoso i actually think it is working. The render of elevation is just not the same on both platforms. Look closely at what happens when you touch the button on android.
Also use a white background. More contrast

**Comment by juanbonoso** [comment]
Setting both buttons to an elevation of 20. 
Is this the normal behavior of the button? The floating button on ios, looks better , more floating.

![Screen Shot 2020-04-14 at 14 03 44](https://user-images.githubusercontent.com/43289624/79263692-e86e8380-7e58-11ea-8b11-8bc6b6d45b60.png)

**Comment by farfromrefug** [comment]
@juanbonoso normal behavior yes. It is how google defines elevations on both platforms. There are always more subtle on android. And personally i prefer it that way.
