### ISSUE TITLE
I would like to contribute

### ISSUE THREAD

**Issue by henrychavez** [Akylas/nativescript-material-components#14]
Hi, I would like to contribute to the repo, and I wanna know if there is someone who I can talk to figure out the best way to do it.

I would like to use this repo more, but I notice that in some cases the documentation isn't enough and some examples with Angular are missing.

Yesterday, I finished some implementation for `BottomSheets` and Angular that can be used for custom Dialogs too, also I notice some errors with the `.d.ts` files that don't export correctly some functions.

Anyway I have a plugin too and I know how difficult can be to maintain, and I wanna help you guys because I think this is a great repo and you have done a lot so far.

**Comment by farfromrefug** [comment]
@henrychavez the best way for now is to create PRs so that i can review and merge them.

Thanks for your help!

**Comment by henrychavez** [comment]
Ok great!
