### ISSUE TITLE
[Vue] How to pass data to and retrieve data in a Bottom Sheet

### ISSUE THREAD

**Issue by ab192130** [Akylas/nativescript-material-components#140]
- Android / Vue

How to pass data to Bottom Sheet and get in Vue?

I use this code to pass data:
```
this.$showBottomSheet(Component, {
                    context: {foo: 'bar'},
                    closeCallback: (result) => {}
                });
```

But CAN'T get the data in the bottom sheet:
```
export default {
        props: ['foo'],
        mounted() {
            console.log('passed_data', this.foo);
        },
    }
```

Can you help me with this? I'll appreciate any help. Thanks so much!

**Comment by farfromrefug** [comment]
@ab192130 you need to look at the typings.
You needs to the use the `props` option key
https://github.com/Akylas/nativescript-material-components/blob/master/src/bottomsheet/vue/index.ts#L7

**Comment by ab192130** [comment]
@farfromrefug, Can you explain me how to do it exactly?
I couldn't find out what is "props - option key". 
I've already added "props" above. What is my actual mistake?

**Comment by farfromrefug** [comment]
@ab192130 you have not. You used props in your component. Not in the `$showBottomSheet` options. change `context` to `props` and it should work.

**Comment by ab192130** [comment]
@farfromrefug Yay! 🎉 It worked. So thanks 🤗
