### ISSUE TITLE
[Textfield - Vue] Can no longer access setPrefixText / setSuffixText functions

### ISSUE THREAD

**Issue by kryoware** [Akylas/nativescript-material-components#149]
I have had no issues with this for months but after adding bottomsheet to my original app, I noticed this function no longer works. Can anyone help me out? This is a very critical part of the app I'm building.

PS: I do not know if this issue is Vue specific

---

1. Created a new Nativescript-Vue project and setup material-components.
2. Installed Textfield plugin
3. Here's how I call the function:
```
<template>
  <StackLayout>
    <MDTextField
      @loaded="loaded"
      :text="user.contact"
    />
  </StackLayout>
</template>

<script>
export default {
  methods: {
    loaded({ object }) {
      object.nativeView.setPrefixText('+63')
    }
  }
}
</script>
```

I just get `setPrefixText is not a function` but this function is accessible if I try to build in Android Studio. Material Design spec also lists this function so I guess the issue lies with a recent change in this plugin.

---

CLI: 6.7.4
Platform: 6.5.1
Plugins: Defaults + Material Textfield

**Comment by farfromrefug** [comment]
I dont think  it has anyhthing to do bottomsheet per say.
It must be the version of android material library. You should check which one is used in one case and the other.

**Comment by kryoware** [comment]
I've always just relied on the version the plugin shipped with in both cases. Thanks for the idea, I used nativescript's hooks to add the right library before the plugin. Had to dig to try the three most recent versions until I found the one that worked like before.

**Comment by farfromrefug** [comment]
@kryoware can you please reference the version for other users?
Thanks

**Comment by kryoware** [comment]
@farfromrefug version 1.2.0-alpha01 worked as intended for me, and did not affect the other material components. Hope it helps, cheers!

**Comment by farfromrefug** [comment]
@kryoware ok that s the one i use too. Thanks
