### ISSUE TITLE
[Feature Request] Add value label to slider

### ISSUE THREAD

**Issue by yringler** [Akylas/nativescript-material-components#15]
The material spec for slider [also discusses a value label](https://material.io/design/components/sliders.html#anatomy) (a label with current value that floats alongside the slider).

I think this is often valuable and should be added.

On android, would have to switch to a slider which supports it; perhaps [this slider](https://github.com/warkiz/IndicatorSeekBar).

**Comment by farfromrefug** [comment]
@yringler This repo tries only to use Google Material Components library as its dependency to make sure we follows material specs.
So right now as both iOS and Android dont have label for sliders i won't add it in this repo.
However you can very simply create an another module depending on ```nativescript-material-slider``` which adds a label 

Hope you understand

**Comment by yringler** [comment]
%100. Another concern of using a non-official slider is always stability. Will make that module when I get to that.

**Comment by yringler** [comment]
That's a very good point of depending on it (instead of forking).
Thank you for your advice.
