### ISSUE TITLE
Bottom sheet border radius is not working

### ISSUE THREAD

**Issue by venkatesh16031999** [Akylas/nativescript-material-components#154]
### Device which occurs
1.Both android and Ios

###reference

![git-issue](https://user-images.githubusercontent.com/45749900/86892421-dd588600-c11d-11ea-9ddf-debf12bf7471.png)

how to add border radius to the bottom sheet ? fix the issue and share the solution

**Comment by farfromrefug** [comment]
It is not possible per say. Use a transparent bottomsheet and round your inner view.

**Comment by venkatesh16031999** [comment]
> It is not possible per say. Use a transparent bottomsheet and round your inner view.

okay how to make the bottom sheet layer transparent ?

**Comment by farfromrefug** [comment]
@venkatesh16031999 please look at the typescript typings
