### ISSUE TITLE
Bottom sheet is not fully opening in small screen half expanded

### ISSUE THREAD

**Issue by venkatesh16031999** [Akylas/nativescript-material-components#155]
@farfromrefug 

i am opening the bottom sheet it is not fully expanded we need to scroll manually 

while opening 

![issue1](https://user-images.githubusercontent.com/45749900/87049179-47565580-c21a-11ea-8b9e-7362c20d4e04.png)

when dragging up only i got full view 

![issue2](https://user-images.githubusercontent.com/45749900/87049253-605f0680-c21a-11ea-852a-0d99a3ab75c3.png)
 
this problem happens in both ios and android can anyone give solution for this 

I am using: "nativescript-material-bottomsheet": "^3.1.15",
Angular version: 8.2.0
Nativescript version: 6.4.1

**Comment by farfromrefug** [comment]
Without sample or screenshots i cant help. Mostly a native behavior. You might be able to change that in the plugin. PR are welcome

**Comment by venkatesh16031999** [comment]
> Without sample or screenshots i cant help. Mostly a native behavior. You might be able to change that in the plugin. PR are welcome

**Comment by venkatesh16031999** [comment]
> @farfromrefug
> 
> i am opening the bottom sheet it is not fully expanded we need to scroll manually
> 
> while opening
> 
> ![issue1](https://user-images.githubusercontent.com/45749900/87049179-47565580-c21a-11ea-8b9e-7362c20d4e04.png)
> 
> when dragging up only i got full view
> 
> ![issue2](https://user-images.githubusercontent.com/45749900/87049253-605f0680-c21a-11ea-852a-0d99a3ab75c3.png)
> 
> this problem happens in both ios and android can anyone give solution for this
> 
> I am using: "nativescript-material-bottomsheet": "^3.1.15",
> Angular version: 8.2.0
> Nativescript version: 6.4.1

**Comment by venkatesh16031999** [comment]
@farfromrefug screenshots attached for your reference

**Comment by farfromrefug** [comment]
You must have gone over a "max peek height" of the native component. Maybe try a smaller one

**Comment by venkatesh16031999** [comment]
@farfromrefug but it is not for all the device only 5.5 inch or below screen size this is happening and i need the same height that i have used now across all the devices

**Comment by farfromrefug** [comment]
@venkatesh16031999 still native behavior. This is how the native is intended to behave, almost sure of that. You can look on their repo.
Nothing i can do here (or need to do right now as not a bug). Again if you want to implement custom max height, PR are welcome!
