### ISSUE TITLE
Bottom Sheet goes up while killing and re-opening the app

### ISSUE THREAD

**Issue by venkatesh16031999** [Akylas/nativescript-material-components#157]
I am using nativescript with angular 

it is happening for the ios devices , in android it works perfect .

1.while we are killing the app and re open the bottom sheet contents goes up in ios

reference for my problem attached below

![issues3](https://user-images.githubusercontent.com/45749900/87521149-98929900-c6a1-11ea-9706-718602312ff9.png)

@farfromrefug quick help is appreciated , thanks

**Comment by farfromrefug** [comment]
i think it is app code related. I dont see that in any of my apps.
If you can create a very simple project to reproduce it and not using angular i can fix it

**Comment by venkatesh16031999** [comment]
actually for my use case i need to continue with angular only

**Comment by farfromrefug** [comment]
@venkatesh16031999 sorry but no fix on my side then. I cant maintain all the frameworks. I ll close this then.
If you can pinpoint the issue to that component please comment and l ll reopen
