### ISSUE TITLE
Request : More examples for Angular 

### ISSUE THREAD

**Issue by alexandruantonica** [Akylas/nativescript-material-components#16]
I'm trying to implement BottomSheet on NS + Angular but unfortunately, there is no demo project and based on `demo` (Plain NS) it doesn't work. 
According to `demo` (Plain NS), it says to get the `showBottomSheet` from a View. I have tried to get it from the `args` object return by the Tap Event like that : 
```
openSelectionModal($event: any): void {

        const obj = $event.object as View;

        obj.showBottomSheet({
            view: '...',
            context : {},
            closeCallback: res => {
                alert(`bottomsheet closed ${JSON.stringify(res)}`);
            }
        });
}
```
Unfortunetly, the TS says `showBottomSheet` does not exist on type `View`. 
The only difference is I am trying to get the `showBottomSheet` from a simple `tap` event from a `StackLayout`. In your example, you are shown how to do this from a Button, but this is not my case and it should work anyway. 

Any help please ?

**Comment by farfromrefug** [comment]
@alexandruantonica I don't work with Angular. So any demo PR is welcome

About your issue. Seems like ```nativescript-material-bottomsheet``` has not been called. This is essential to get the ```showBottomSheet``` override.
Will try to add a way to do it without that override (install) requirement

**Comment by henrychavez** [comment]
@alexandruantonica I adapted the bottom-sheet implementation to work with angular I can share with you the code, and also I'll create a pull request this weekend to be part of the library by default with some examples too, but the problems with the typings must be solved because sometimes you can get some errors with webpack

**Comment by alexandruantonica** [comment]
@henrychavez Please share the example here.

**Comment by henrychavez** [comment]
@alexandruantonica check this PR #27

**Comment by alexandruantonica** [comment]
Thanks @henrychavez
