### ISSUE TITLE
Tabs do not work with Nativescript/Angular 10

### ISSUE THREAD

**Issue by boris01** [Akylas/nativescript-material-components#164]
Hi,
When ever I try to build the app, I get this error:

ERROR in node_modules/@nativescript-community/ui-material-tabs/angular/index.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of HomeModule, but could not be resolved to an NgModule class.

This likely means that the library (@nativescript-community/ui-material-tabs/angular) which declares NativeScriptMaterialTabsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to 
see if the library is expected to be compatible with Ivy.

export declare class NativeScriptMaterialTabsModule

**Comment by farfromrefug** [comment]
@boris01 what version are you using?

**Comment by boris01** [comment]
4.0.5

**Comment by boris01** [comment]
@farfromrefug 
The same thing also happens  with Bottom Navigation Bar. 
I tried versions 4.0.4 - 4.0.6.
Thanks

**Comment by NathanWalker** [comment]
@boris01 There were some NativeClass decorations missing, fix published in 4.0.9 👍 Let us know if have any other trouble.
