### ISSUE TITLE
`nativescript-material-botttomsheet` has no exported member `install` 

### ISSUE THREAD

**Issue by alexandruantonica** [Akylas/nativescript-material-components#17]
`install` method is not found in `nativescript-material-bottomsheet` and I had to use it as I saw in one of your example, from `nativescript-material-core` but I am not sure it is the same. 
Also, this is not the way it should work, to import it from another module even if it is the core.

**Comment by farfromrefug** [comment]
@alexandruantonica needs more details (log). Cant reproduce it here

**Comment by alexandruantonica** [comment]
@farfromrefug 
According to this [documentation](https://market.nativescript.org/plugins/nativescript-material-bottomsheet#typescript), `install()` must be exported by the module `nativescript-material-bottomsheet` but [it is not exported](https://github.com/Akylas/nativescript-material-components/blob/4b4b2c86b8158aaf33a5e1b068edec00bdd7d813/src/bottomsheet/bottomsheet.d.ts#L11). In order to make it work, I need to import the `install` [method](https://github.com/Akylas/nativescript-material-components/blob/4b4b2c86b8158aaf33a5e1b068edec00bdd7d813/src/core/core.ios.ts#L61) from `nativescript-material-core`. 

It is quite unusual to import methods for a specific child module from the parent module (`core`). In my point of view, a `core` module is used only in case when you have parts of the functionality in multiple child modules. Indeed, in this case, you have a lot of common functionality but I don't see the scope of the `install` method from `core` that install `bottomsheet`. 
I hope it does make sense of what I said. Let me know if you need more info.

**Comment by farfromrefug** [comment]
@alexandruantonica ok it s a typings error. You could fix simply using ```require('nativescript-bottomsheet').install()```
However will be fixed in the next version.

Also latest version already stopped running sub modules install from the core one

**Comment by alexandruantonica** [comment]
@farfromrefug Cool. Thanks ;)

**Comment by farfromrefug** [comment]
@alexandruantonica can you close this?

**Comment by alexandruantonica** [comment]
@farfromrefug Sure
