### ISSUE TITLE
Button is always blue (Android)

### ISSUE THREAD

**Issue by joshcomley** [Akylas/nativescript-material-components#19]
### Make sure to check the demo app(s) for sample usage 
I've checked but can't find anything.

### Make sure to check the existing issues in this repository 
Done

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Normal material button seems to not honour the theme colour, whereas floating-action-button etc. do:

![2019-06-08 00_26_25-5CAd56_hpfynZMnTVkWlof4qYTK60wNjzVe8ob8wYGpzNUVyJvmNIBm7XbFFF337l3XTdvent1Tvybw_](https://user-images.githubusercontent.com/820534/59138276-1efb8800-8984-11e9-9192-587cb0b27a49.png)

How can I make the button use the theme colour?

### Which platform(s) does your issue occur on?
- Android

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.4.0
- Cross-platform modules: 5.4.2
- Runtime(s): 5.4.0

**Comment by joshcomley** [comment]
I'll also add I did copy `styles.xml` across from the demo project, which got the floating action button working with the theme colour.

Having inspected the source, in floating action button you set:

                if (value.color) {
                    this.nativeViewProtected.setBackgroundTintList(android.content.res.ColorStateList.valueOf(value.color.android));
                }

Whereas in standard button you set:

                if (value.color) {
                    this.nativeViewProtected.setBackgroundTintList(getEnabledColorStateList(value.color.android, this.variant));
                }

Is perhaps the first one the correct one? I'm not 100% sure but thought I'd propose an idea!

Thanks so much.

**Comment by joshcomley** [comment]
OK upon closer inspection of the source, I've figured it out: I was missing `materialstyles.xml` from the demo project, which I had previously copied but it had caused errors which I've since resolved but not put it back.

Thanks again for this package, I may well contribute myself if you wouldn't mind!

Cheers,
Josh

**Comment by farfromrefug** [comment]
@joshcomley yes sorry about this one. This should be in the doc.
This is the way it is on android. Still it is on my mind to make the themer work on andorid too
