### ISSUE TITLE
Improve Vue integration + Vue demo

### ISSUE THREAD

**Issue by msaelices** [Akylas/nativescript-material-components#3]
Improve Vue support for all existing MD components. That is:

* Allow using it as Vue plugins, like that:
```
import FooPlugin from 'nativescript-material-foo/vue';
Vue.use(FooPlugin);
``` 
* Allow the use of `v-model` directive for binding dynamic instance data where applicable.
* Adapt the READMEs
* Implement a Vue demo app that tests all the components.

Components to implement:
- [x] MDButton
- [x] MDFloatingActionButton
- [x] MDTextField
- [x] MDProgress
- [x] MDActivityIndicator
- [x] MDSlider
- [x] MDRipple
- [x] MDCardView
- [ ] MDSnackBar
- [ ] Dialogs
- [ ] Bottom Sheet
- [ ] MDAppBar

**Comment by fvdung** [comment]
You intend to continue implements for `Dialogs` and `Bottom Sheet` for Vuejs?

**Comment by farfromrefug** [comment]
@msaelices There is no need for imports for Dialogs and BottomSheet. Except maybe for bottomsheet which needs to call its install method because it needs to use mixins on ```View```
Same thing for snackbar actually.
And MDAppBar is not functional nor published

about v-model. Not possible sadly due to the implemetation of ```nativescript-vue```. Well it does work if you define it yourself in the webpack config like this:
```
// temporary hack to support v-model using ns-vue-template-compiler
// See https://github.com/nativescript-vue/nativescript-vue/issues/371
NsVueTemplateCompiler.registerElement('MDTextField', () => require('nativescript-material-components/textfield').TextField, {
    model: {
        prop: 'text',
        event: 'textChange'
    }
});
NsVueTemplateCompiler.registerElement('MDSlider', () => require('nativescript-material-components/slider').Slider, {
    model: {
        prop: 'value',
        event: 'valueChange'
    }
});
```

Now on a side not for Dialogs and BottomSheets which uses custom "view" right now you need to pass the vue instance ```nativeView``` (the actual ```View``` object) object.

**Comment by fvdung** [comment]
What I expect is the use of a custom .vue file for dialogs and Bottom Sheet

**Comment by farfromrefug** [comment]
@fvdung  can you explain. I don't understand what you mean. thanks

**Comment by farfromrefug** [comment]
@fvdung  you can. mount the vue component and use the view option

**Comment by fvdung** [comment]
I catch error `TypeError: moduleName.trim is not a function` when use view option with XML file (.vue)
```
    import BottomView from './bottom_view.vue'

    ......
    methods: {
          showBottomMenu(args) {
                 args.object.showBottomSheet({
                        view: BottomView,
                        context: {data: 'test'},
                        closeCallback: (data) => {
                            console.log(data)
                        }
                  })
          }
    }
```
What is invalid in my code?

**Comment by farfromrefug** [comment]
@fvdung as i said you need to mount your vue component so that you can pass the nativeView object. Something like this:
```ts
 const instance = new (require('./LoadingIndicator.vue').default)();
instance.$mount();
const view = instance.nativeView;
```

**Comment by fvdung** [comment]
thanks @farfromrefug I'll try it

**Comment by juanrdlo** [comment]
the same error still appears. what you are indicating does not work

**Comment by farfromrefug** [comment]
@juanrdlo it should work. please share full example to reproduce. Any log error is also useful

**Comment by juanrdlo** [comment]
I'm sorry for not responding, I've been a little busy, today I will upload the project so you can verify the error.

Regards
