### ISSUE TITLE
[Feature Request] add ability to use reactive forms with mdtextfield

### ISSUE THREAD

**Issue by inONEL** [Akylas/nativescript-material-components#33]

**Comment by inONEL** [comment]
Here's a temporary solution. Create a temporary text-value-accessor directive and add it to your module.
`import { Directive, ElementRef, forwardRef } from '@angular/core';
import { NG_VALUE_ACCESSOR } from '@angular/forms';
import { View } from 'tns-core-modules/ui/core/view';
import {BaseValueAccessor} from 'nativescript-angular';

const TEMP_TEXT_VALUE_ACCESSOR = {
  provide: NG_VALUE_ACCESSOR,
  useExisting: forwardRef(() => TempTextValueAccessor),
  multi: true,
};

export type TextView = {text: string} & View;

/**
 * The accessor for writing a text and listening to changes that is used by the
 * {@link NgModel} directives.
 *
 *  ### Example
 *  ```
 *  <TextField [(ngModel)]="model.test">
 *  ```
 */
@Directive({
  selector:
    'MDTextField[ngModel],MDTextField[formControlName],MDTextField[formControl]',
  providers: [TEMP_TEXT_VALUE_ACCESSOR],
  host: {
    '(blur)': 'onTouched()',
    '(textChange)': 'onChange($event.value)',
  },
})
export class TempTextValueAccessor extends BaseValueAccessor<TextView> { // tslint:disable-line:directive-class-suffix
  constructor(elementRef: ElementRef) {
    super(elementRef.nativeElement);
  }

  writeValue(value: any): void {
    const normalized = super.normalizeValue(value);
    this.view.text = normalized;
  }
}
`

**Comment by farfromrefug** [comment]
@inONEL actually it is already implemented [here](https://github.com/Akylas/nativescript-material-components/blob/master/src/textfield/angular/textvalue-accessor.ts)

**Comment by diegovincent** [comment]
Same issue here, duplicated of #66

**Comment by diegovincent** [comment]
It does not work with the already implemented accesor.

**Comment by farfromrefug** [comment]
@diegovincent really cant help on this one as i dont use angular. Really sorry :s

**Comment by diegovincent** [comment]
I confirm it now works. For those of you out there, I simply made the mistake that I was using MDTextField on one module, and then imported that module into ANOTHER module, but if that is the case, this second module must import the Material Design Module as well.

**Comment by cesaralcoba** [comment]
> @inONEL actually it is already implemented [here](https://github.com/Akylas/nativescript-material-components/blob/master/src/textfield/angular/textvalue-accessor.ts)

Hi, i'm trying to use reactive forms with mdtextfield how can i use with the textvalue-accessor??  i have implemented like
` <MDTextField
                            formControlName="rut"
                            helper="Ej: 13.654.988-k"
                            hint="RUT"
                            variant="outline"
                            returnKeyType="next"
                            (focus)="onFocus($event)"
                            (blur)="onBlur($event)"
                            (textChange)="onTextChange($event)"
                        ></MDTextField>`
But i had this error:
  **No value accessor for form control with name:**
can you help me???
