### ISSUE TITLE
calling js method onCreateView failed

### ISSUE THREAD

**Issue by juanrdlo** [Akylas/nativescript-material-components#34]
Hi, I'm trying to add the material button but I get the following error.

I have placed these directives in the app.js file :
import Vue from 'nativescript-vue';
import ButtonPlugin from 'nativescript-material-button/vue';
 
Vue.use(ButtonPlugin);

but when placing the tag I get that error. can you help me?...

An uncaught Exception occurred on "main" thread.
Calling js method onCreateView failed
Error: android.content.res.Resources$NotFoundException: Resource ID #0x0
    android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
    android.content.res.Resources.loadXmlResourceParser(Resources.java:2148)
    android.content.res.Resources.getLayout(Resources.java:1157)
    android.view.LayoutInflater.inflate(LayoutInflater.java:421)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
    com.tns.Runtime.callJSMethod(Runtime.java:1109)
    com.tns.Runtime.callJSMethod(Runtime.java:1089)
    com.tns.Runtime.callJSMethod(Runtime.java:1081)
    com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
    androidx.fragment.app.Fragment.performCreateView(Fragment.java:2612)
    androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:874)
    androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
    androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
    androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
    androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2066)
    androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1856)
    androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
    androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
    androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
    android.os.Handler.handleCallback(Handler.java:789)
    android.os.Handler.dispatchMessage(Handler.java:98)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6944)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

StackTrace:
	Frame: function:'Button.createNativeView', file:'file:///data/data/org.nativescript.educontrol/files/app/vendor.js', line: 460, column: 64
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.educontrol/files/app/vendor.js', line: 35198, column: 25
	Frame: function:'', file:'file:///data/data/org.nativescript.educontrol/files/app/vendor.js', line: 35253, column: 13
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.educontrol/files/app/vendor.js', line: 46286, column: 20
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.educontrol/files/app/vendor.js', line: 36699, column: 10
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.educontrol/files/app/vendor.js', line: 35252, column: 10
	Frame: function:'', file:'file:///data/data/org.nativescript.educontrol/files/app/vendor.js', line: 35253, column: 13
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.educontrol/files/app/vendor.js', line: 32462, column: 7
	Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.educontrol/files/app/vendor.js', line: 47726, column: 36
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.educontrol/files/app/vendor.js', line: 36699, column: 10
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.educontrol/files/app/vendor.js', line: 35252, column: 10
	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.educontrol/files/app/vendor.js', line: 35123, column: 12
	Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.educontrol/files/app/vendor.js', line: 35106, column: 10
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.educontrol/files/app/vendor.js', line: 42625, column: 13
	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.educontrol/files/app/vendor.js', line: 40078, column: 34
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
	at com.tns.Runtime.callJSMethod(Runtime.java:1109)
	at com.tns.Runtime.callJSMethod(Runtime.java:1089)
	at com.tns.Runtime.callJSMethod(Runtime.java:1081)
	at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2612)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:874)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2066)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1856)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2148)
	at android.content.res.Resources.getLayout(Resources.java:1157)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
	... 24 more

**Comment by farfromrefug** [comment]
@juanrdlo Seems like an issue with {N}. Can you share your package.json

**Comment by juanrdlo** [comment]
my package,json on folder app
`{
  "main": "app.js",
  "android": {
    "v8Flags": "--expose_gc",
    "markingMode": "none"
  }
}
`


My package.json global
`{
  "nativescript": {
    "id": "org.nativescript.educontrol",
    "tns-ios": {
      "version": "6.0.1"
    },
    "tns-android": {
      "version": "6.0.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "nativescript-material-core": "2.3.4",
    "nativescript-material-ripple": "^2.3.6",
    "nativescript-pulltorefresh": "^2.3.0",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-vue": "~2.3.0",
    "tns-core-modules": "~6.0.0"
  },
  "devDependencies": {
    "@babel/core": "~7.1.0",
    "@babel/preset-env": "~7.1.0",
    "babel-loader": "~8.0.0",
    "nativescript-dev-webpack": "~1.0.0",
    "nativescript-material-button": "2.3.4",
    "nativescript-vue-template-compiler": "~2.3.0",
    "node-sass": "^4.7.1",
    "vue-loader": "~15.4.0"
  },
  "gitHead": "f28dbc60d74dd2cef4b645afd8fdd63bbb12c73e",
  "readme": "NativeScript Application"
}
`

**Comment by henrychavez** [comment]
@juanrdlo u need to use the androidx branch with NS6

**Comment by farfromrefug** [comment]
@juanrdlo @henrychavez   you seem to be using 2.3.4 which is N 6 compatible
from now on  all master releases use androidx .

**Comment by juanrdlo** [comment]
> @juanrdlo @henrychavez you seem to be using 2.3.4 which is N 6 compatible
> from now on all master releases use androidx .

I do not understand, so what is the solution to be able to run the plugin?

**Comment by farfromrefug** [comment]
@juanrdlo not sure. MAybe a full clean (node_modules, platforms, hooks...)

**Comment by akadlec** [comment]
same issue here :/

**Comment by akadlec** [comment]
package.json
```
{
  "dependencies": {
    "core-js": "^2.6.5",
    "nativescript-material-button": "^2.3.16",
    "nativescript-material-textfield": "^2.3.16",
    "nativescript-socketio": "^3.3.1",
    "nativescript-toasty": "^2.0.1",
    "nativescript-vue": "^2.2.2",
    "nativescript-vue-devtools": "^1.2.0",
    "tns-core-modules": "6.0.1",
    "vue": "^2.6.10",
    "vue-cli-plugin-i18n": "^0.6.0",
    "vue-i18n": "^8.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/preset-env": "^7.4.5",
    "@babel/traverse": "^7.4.5",
    "@vue/cli-plugin-babel": "^3.9.0",
    "@vue/cli-plugin-eslint": "^3.9.0",
    "@vue/cli-service": "^3.9.0",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.6",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "nativescript-dev-webpack": "1.0.1",
    "nativescript-vue-template-compiler": "^2.2.2",
    "nativescript-worker-loader": "~0.9.5",
    "node-sass": "^4.11.0",
    "patch-package": "^6.1.2",
    "rimraf": "^2.6.3",
    "sass-loader": "^7.1.0",
    "string-replace-loader": "^2.1.1",
    "vue-cli-plugin-nativescript-vue": "^0.1.3",
    "vue-template-compiler": "^2.6.10",
    "webpack-cli": "^3.3.6"
  },
  "nativescript": {
    "id": "org.nativescript.application",
    "tns-ios": {
      "version": "6.0.1"
    },
    "tns-android": {
      "version": "6.0.0"
    }
  }
}
```

**Comment by akadlec** [comment]
cleared platforms, node_modules and hooks

**Comment by akadlec** [comment]
ok used `App_Resource` from demo and it is working now

**Comment by juanrdlo** [comment]
> cleared platforms, node_modules and hooks

> ok used `App_Resource` from demo and it is working now

I have installed nativescripts since 0 and I have only installed this plugin, and it does not work. I have done a cleaning, and it sends me the same error. what I understand is that when using Vue.use (Button) it does not recognize it in the <MDButton> tag

**Comment by farfromrefug** [comment]
@juanrdlo how do you create your app repo? What version of {N} are you using?
Mostly this comes from using androidx. Something in your config might not work.
