### ISSUE TITLE
Nesting buttons within StackLayouts increases the elevation shadow

### ISSUE THREAD

**Issue by joshcomley** [Akylas/nativescript-material-components#37]
### Make sure to check the demo app(s) for sample usage 
Checked

### Make sure to check the existing issues in this repository 
Checked

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
Each time you nest an `MDButton` in a StackLayout, the elevation shadow increases even if it is specified explicitly.

### Which platform(s) does your issue occur on?
- Android (can't check iPhone just right now)
- v7.0
- ASUS ZenPad 3s

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.0.2
- Cross-platform modules: 6.0.1
- Runtime(s): 6.0.1
- Plugin(s): material plugins at 2.3.10

### Please, tell us how to recreate the issue in as much detail as possible. 
Although this also happens within nested Angular controls, you can recreate this problem by pasting this code into any project that has the material button plugin:

	<StackLayout>
		<MDButton elevation="10" text="Test me"></MDButton>
		<StackLayout>
			<MDButton elevation="10" text="Test me"></MDButton>
			<StackLayout>
				<MDButton elevation="10" text="Test me"></MDButton>
				<StackLayout>
					<MDButton elevation="10" text="Test me"></MDButton>
					<StackLayout>
						<MDButton elevation="10" text="Test me"></MDButton>
						<StackLayout>
							<MDButton elevation="10" text="Test me"></MDButton>
							<StackLayout>
								<MDButton elevation="10" text="Test me"></MDButton>
								<StackLayout>
									<MDButton elevation="10" text="Test me"></MDButton>
									<StackLayout>
										<MDButton elevation="10" text="Test me"></MDButton>
										<StackLayout>
											<MDButton elevation="10" text="Test me">
											</MDButton>
											<StackLayout>
												<MDButton elevation="10" text="Test me">
												</MDButton>
												<StackLayout>
													<MDButton elevation="10" text="Test me">
													</MDButton>
													<StackLayout>
														<MDButton elevation="10"
															text="Test me"></MDButton>
														<StackLayout>
															<MDButton elevation="10"
																text="Test me"></MDButton>
														</StackLayout>
													</StackLayout>
												</StackLayout>
											</StackLayout>
										</StackLayout>
									</StackLayout>
								</StackLayout>
							</StackLayout>
						</StackLayout>
					</StackLayout>
				</StackLayout>
			</StackLayout>
		</StackLayout>
	</StackLayout>

You will see something like this:

![image](https://user-images.githubusercontent.com/820534/62047658-f1ec8880-b202-11e9-85cb-42327a8e9238.png)

**Comment by farfromrefug** [comment]
@joshcomley that s a funny issue!
Will look into it

**Comment by joshcomley** [comment]
Bloody hell that was quick. Lovely, thank you!!

**Comment by farfromrefug** [comment]
@joshcomley cant get the same view as you. My shadows are not as sharp. Do you have a special android/res/values/styles.xml ?

**Comment by joshcomley** [comment]
@farfromrefug This is my `styles.xml`:

    <resources xmlns:android="http://schemas.android.com/apk/res/android">
        
        <style name="LaunchScreenThemeBase" parent="Theme.MaterialComponents.Light.NoActionBar">
            <item name="toolbarStyle">@style/NativeScriptToolbarStyle</item>
            <item name="colorPrimary">@color/ns_primary</item>
            <item name="colorPrimaryDark">@color/ns_primaryDark</item>
            <item name="colorAccent">@color/ns_accent</item>
            <item name="android:windowBackground">@drawable/splash_screen</item>
            <item name="android:windowActionBarOverlay">true</item>
            <item name="android:windowTranslucentStatus">true</item>
        </style>
        <style name="LaunchScreenTheme" parent="LaunchScreenThemeBase"></style>
        
        <style name="AppThemeBase" parent="Theme.MaterialComponents.Light.NoActionBar">
            <item name="toolbarStyle">@style/NativeScriptToolbarStyle</item>
            <item name="colorPrimary">@color/ns_primary</item>
            <item name="colorPrimaryDark">@color/ns_primaryDark</item>
            <item name="colorAccent">@color/ns_accent</item>
        </style>
        <style name="AppTheme" parent="AppThemeBase"></style>
        
        <style name="NativeScriptToolbarStyleBase" parent="Widget.AppCompat.Toolbar">
            <item name="android:background">@color/ns_primary</item>
            <item name="theme">@style/ThemeOverlay.AppCompat.ActionBar</item>
            <item name="popupTheme">@style/ThemeOverlay.AppCompat</item>
        </style>
        <style name="NativeScriptToolbarStyle" parent="NativeScriptToolbarStyleBase"></style>
    </resources>

**Comment by joshcomley** [comment]
Just checked and it's identical to the ng demo on here except for spacing

**Comment by joshcomley** [comment]
I did have a `materialstyles.xml` which I believe used to be a requirement for using this plugin not so long ago, I've now removed that and rebuilt - but I get the same result. For the purposes of testing (and the screenshot) I also removed all CSS from the project, which certainly made a thicker shadow.

If I put the CSS back in, I get this, which may be more akin to what you're seeing:

![image](https://user-images.githubusercontent.com/820534/62057288-46016800-b217-11e9-8ae2-45d82c55999d.png)

**Comment by farfromrefug** [comment]
@joshcomley weird even between your 2 screenshots your shadows dont look the same. A lot more blurry on the first one. Trying to use inverted colors to see if i have the issue here or if it is something related to the platform. 
Do you see the same issue on the emulator?
On your device is is a constructor version of android?

**Comment by farfromrefug** [comment]
Ok Using this 
```xml
 <StackLayout>
                <MDButton elevation="5" text="Test me1" backgroundColor="white" />
                <StackLayout>
                    <StackLayout>
                        <StackLayout>
                            <StackLayout>
                                <StackLayout>
                                    <StackLayout>
                                        <StackLayout>
                                            <MDButton elevation="5" text="Test me2" backgroundColor="white" />
                                            <StackLayout>
                                                <StackLayout>
                                                    <StackLayout>
                                                        <StackLayout>
                                                            <StackLayout>
                                                                <StackLayout>
                                                                    <StackLayout>
                                                                        <StackLayout>
                                                                            <StackLayout>
                                                                                <StackLayout>
                                                                                    <StackLayout>
                                                                                        <StackLayout>
                                                                                            <MDButton elevation="5" text="Test me3" backgroundColor="white" />
                                                                                        </StackLayout>
                                                                                    </StackLayout>
                                                                                </StackLayout>
                                                                            </StackLayout>
                                                                        </StackLayout>
                                                                    </StackLayout>
                                                                </StackLayout>
                                                            </StackLayout>
                                                        </StackLayout>
                                                    </StackLayout>
                                                </StackLayout>
                                            </StackLayout>
                                        </StackLayout>
                                    </StackLayout>
                                </StackLayout>
                            </StackLayout>
                        </StackLayout>
                    </StackLayout>
                </StackLayout>
            </StackLayout>
```
i dont see any issue
<img width="634" alt="Screen Shot 2019-07-29 at 16 47 35" src="https://user-images.githubusercontent.com/655344/62057829-a5b04100-b220-11e9-864c-c08198ee7c27.png">

However i did rewrite my elevation handling to match {N} 6 ```androidElevation``` and ```androidDynamicElevationOffset```.
So i now use ```elevation``` and ```dynamicElevationOffset```

Please try on the emulator to see. Will publish a new version really soon

**Comment by joshcomley** [comment]
Ah, I should also mention that I am using `nativescript-theme-core` v2.0.2, and this is in some way affecting the shadows. This was stripped out for the original screenshot for testing purposes.

I will test on an emulator now and get back to you - shall I wait for the new version to test, or would you like me to test as-is on the emulator, also?

One question: what do you mean by "constructor version of android"?

**Comment by farfromrefug** [comment]
Please test with the current version. If it happens, we will test with the new one.

I mean your OS, is it the default Asus version? If so it might be modified by Asus

**Comment by joshcomley** [comment]
Ah OK, it's the default, yes. I'll test on other Android devices now, some Samsung ones, and the emulator.

**Comment by joshcomley** [comment]
I've just tested on a Samsung SM-T585 tablet and it's the same, however my emulator won't start at all so I can't test on that, unfortunately - just yet.

**Comment by joshcomley** [comment]
I've just tested with the latest version (2.3.11) and I still get the same results. I notice your `MDButton` is self closing - are you testing in a vanilla NS app? I am using Angular, not sure if this affects things.

**Comment by farfromrefug** [comment]
@joshcomley i am using vue. should not change anything. 
Will try to reproduce on some of my device. For now i can't
BTW i am thinking this might be something with android. But i am really not sure.
Let me know if you manage to make it work on emulator

**Comment by joshcomley** [comment]
A little bit more testing reveals the nested `StackLayout` is a bit of a red herring; I get the same result with this:

    <ScrollView>
        <StackLayout [ngStyle]="{'background-color': 'green'}">
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me1">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me2">
            </MDButton>
            <MDButton class="-primary -rounded-sm" elevation="20" text="Test me3">
            </MDButton>
        </StackLayout>
    </ScrollView>

As per this rather beautiful screenshot:

![image](https://user-images.githubusercontent.com/820534/62061427-0f2f5000-b21f-11e9-95c6-ee20da146867.png)

**Comment by farfromrefug** [comment]
@joshcomley ok now that s weird!!!!!
Could it be angular ... Will need to try it with angular

**Comment by joshcomley** [comment]
This code doesn't look right to me:

    [elevationProperty.setNative](value: number) {
        console.log('elevationProperty', value);
        if (isPostLollipop()) {
            createStateListAnimator(this, this.nativeViewProtected); // Shouldn't this still be .setElevation(..)?
        } else {
            this.nativeViewProtected.setElevation(value);
        }
    }
    [dynamicElevationOffsetProperty.setNative](value: number) {
        if (isPostLollipop()) {
            createStateListAnimator(this, this.nativeViewProtected);
        } else {
            this.nativeViewProtected.setTranslationZ(value);
        }
    }

Is the animator not for shifting the position of the shadow? However, my monkey patch to try replacing it with `this.nativeViewProtected.setElevation(value);` didn't fix anything.

In fact, just done a bit more testing: if I comment out the `elevation` and `dynamicElevationOffset` properties, I get *exactly* the same result. So it seems the `setElevation(..)` call is doing nothing. Which is weeeiiird.

**Comment by joshcomley** [comment]
Does this help at all:

Source: https://www.programcreek.com/java-api-examples/index.php?api=android.animation.AnimatorInflater

	@SuppressLint("NewApi")
	private void init(Context context, AttributeSet attributeSet) {
		mVisible = true;
		mColorNormal = getColor(R.color.material_blue_500);
		mColorPressed = darkenColor(mColorNormal);
		mColorRipple = lightenColor(mColorNormal);
		mColorDisabled = getColor(android.R.color.darker_gray);
		mType = TYPE_NORMAL;
		mShadow = true;
		mScrollThreshold = getResources().getDimensionPixelOffset(R.dimen.fab_scroll_threshold);
		mShadowSize = getDimension(R.dimen.fab_shadow_size);
		if (hasLollipopApi()) {
			StateListAnimator stateListAnimator = AnimatorInflater.loadStateListAnimator(context,
					R.animator.fab_press_elevation);
			setStateListAnimator(stateListAnimator);
		}
		if (attributeSet != null) {
			initAttributes(context, attributeSet);
		}
		updateBackground();
	}

Currently, in `utils`, `new android.animation.StateListAnimator(..)` is called, but I can see a similar approach was replaced with layout inflation in the button init.

**Comment by joshcomley** [comment]
So, further update, it seems at least one part of what I'm experiencing is *part of Material Design spec*!!

If you pop about 100 buttons in a `StackLayout` within a `ScrollView`, and scroll to the bottom, you'll see the top visible button and the bottom visible button look exactly the same as the top and bottom visible button *before* you scrolled.

You can read a bit about it here:

https://blog.usejournal.com/playing-with-elevation-in-android-91af4f3be596

Skip to the bit with this picture:

![image](https://user-images.githubusercontent.com/820534/62068561-275a9b80-b22e-11e9-9f99-e71397a93aac.png)

I am trying to find the official reference in the Material Design specs.

I think for buttons this is a very bad idea, as the change is dramatic from top to bottom on a tablet, which is perhaps why inflating the right layout for the state list animator might help - maybe the button layout would stop this happening? I'm not sure how to implement that, though.

Additionally, I am unable to change the value of the shadow once I put `nativescript-theme-core` in place, not sure if that is something to mention here or there.

**Comment by farfromrefug** [comment]
@joshcomley that might explain a lot, especially why i was not seeing it!
Also about the ```nativescript-theme-core``` i know what's happening. {N} define android elevation using the ```androidElevation``` property. I guess they define a default one in the themes. And sadly there is no rule to define in which order property are applied.
So what happens is that ```androidElevation``` is applied after ```elevation``` and override your state list animator.
Will fix this for material components in the next release

**Comment by joshcomley** [comment]
@farfromrefug wonderful, thank you for the explanation. Looking forward to the next release!

**Comment by joshcomley** [comment]
@farfromrefug testing with 2.3.13, elevation now correctly sets elevation - so this can probably be closed unless you have further investigation to conduct? Thanks so much for the efforts

**Comment by farfromrefug** [comment]
@joshcomley great to hear it is fixed! Let's close this one. Will talk to the {N} team on how to correctly handle this in the future
