### ISSUE TITLE
Material Textfield underline variant Android

### ISSUE THREAD

**Issue by inONEL** [Akylas/nativescript-material-components#39]
When I use the underline variant in Android I'm not seeing any underline
![2019-07-31_15h07_15](https://user-images.githubusercontent.com/42933321/62214212-e33dd700-b3a4-11e9-8f89-5fa098bcf972.png)
With ouline or filled I can see the outline in the primary color.
Also the underline variant in IOS is showing an underline

**Comment by farfromrefug** [comment]
@inONEL first underline variant is about to disappear. It s not part of the Material Design anymore.
That's actually why you are not seeing the underline.
This deprecation came with androidX support. Sorry can't really do anything about it.
