### ISSUE TITLE
Not possible to set variant (outline, filled) dynamically

### ISSUE THREAD

**Issue by inONEL** [Akylas/nativescript-material-components#40]
This works: 
<MDTextField variant="outline"></MDTextField>

This doesn't:
<MDTextField [variant]="input.variant"></MDTextField>
<MDTextField variant="{{input.variant}}"></MDTextField>

Dynamically it always returns the filled variant.

**Comment by farfromrefug** [comment]
@inONEL indeed this is not possible. On both platform you need to recreate the view to change the variant.
