### ISSUE TITLE
Android Build fails when trying to use nativescript-material-textfield

### ISSUE THREAD

**Issue by JCFowler** [Akylas/nativescript-material-components#41]
My project works completely fine both on iOS and Android, but when I download the package nativescript-material-textfield, iOS still works but Android fails with this:

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules guava-18.0.jar (com.google.guava:guava:18.0) and listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0)

I deleted and update npm and the project works again. 

I then tired to download only, nativescript-material-core, and I get the same error. 

Here is my dependencies in package.json:

  "dependencies": {
    "@angular/animations": "8.0.0",
    "@angular/common": "8.0.0",
    "@angular/compiler": "8.0.0",
    "@angular/core": "8.0.0",
    "@angular/forms": "8.0.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "8.0.0",
    "@angular/platform-browser-dynamic": "^8.1.3",
    "@angular/router": "8.0.0",
    "@fortawesome/angular-fontawesome": "0.4.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.18",
    "@fortawesome/free-solid-svg-icons": "^5.8.2",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@ngxs-labs/emitter": "^1.9.0",
    "@ngxs/store": "^3.5.0",
    "@nstudio/nativescript-loading-indicator": "^1.0.0",
    "ajv": "^6.10.0",
    "bootstrap": "^4.3.1",
    "core-js": "3.1.4",
    "i": "^0.3.6",
    "jquery": "^3.4.1",
    "nativescript-angular": "^8.1.0",
    "nativescript-audio": "^5.0.2",
    "nativescript-azure-mobile-apps": "^2.0.3",
    "nativescript-background-http": "^3.4.1",
    "nativescript-camera": "^4.5.0",
    "nativescript-cardview": "^3.2.0",
    "nativescript-drawingpad": "^3.1.0",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-imagepicker": "^6.3.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-local-notifications": "^4.0.1",
    "nativescript-material-textfield": "^2.3.16",
    "nativescript-permissions": "^1.3.6",
    "nativescript-photo-editor": "^1.1.0",
    "nativescript-plugin-firebase": "^9.0.4",
    "nativescript-secure-storage": "^2.4.0",
    "nativescript-theme-core": "^1.0.6",
    "nativescript-ui-dataform": "5.0.0",
    "nativescript-ui-listview": "7.0.0",
    "nativescript-ui-sidedrawer": "7.0.0",
    "npm": "^6.10.2",
    "popper.js": "^1.15.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.3.3",
    "tns-core-modules": "^6.1.0-next-2019-08-05-140314-02",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.9",
    "@angular/cli": "^7.3.9",
    "@angular/compiler-cli": "8.0.0",
    "@nativescript/schematics": "~0.6.0",
    "@types/jasmine": "2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "12.6.3",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.1.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "nativescript-dev-webpack": "1.0.0",
    "node-sass": "4.12.0",
    "protractor": "^6.0.0",
    "tns-platform-declarations": "6.0.1",
    "ts-node": "8.3.0",
    "tslint": "5.18.0",
    "typescript": "3.4.5"
  }
}

**Comment by farfromrefug** [comment]
Strange never saw that error plus we don't use guava. But maybe google material uses it.
The error might come from the use of 2 plugins together. Especially i think the error comes from [```nativescript-azure-mobile-apps```](https://github.com/PeterStaev/nativescript-azure-mobile-apps/blob/master/platforms/android/include.gradle). Not sure how to solve it

**Comment by vytautas-pranskunas-** [comment]
same here
