### ISSUE TITLE
TextField and VUE and model not working

### ISSUE THREAD

**Issue by akadlec** [Akylas/nativescript-material-components#42]
When i add `v-model` in the text field, i got an error `JS: [Vue warn]: You may have an infinite update loop in a component render function.` and i am not able to use this field.

**Comment by farfromrefug** [comment]
I think the error might come from somewhere else. No such error in the demo app.

Can you share your sample code

**Comment by akadlec** [comment]
Sorry not, dropped this lib, using own solution

**Comment by cypherix93** [comment]
Still same issue. `JS: [Vue warn]: You may have an infinite update loop in a component render function.` when using `v-model`. All good when no `v-model`.

**Comment by farfromrefug** [comment]
@cypherix93 look at the demo vue webpack config. You need to register the v models

**Comment by cypherix93** [comment]
@farfromrefug Thanks for the response. Shouldn't that just work if I `Vue.use(...)` the plugin? Looks like it's already defined [here](https://github.com/nativescript-community/ui-material-components/blob/master/src/textfield/vue/index.ts#L9).

**Comment by farfromrefug** [comment]
@cypherix93 sadly it is not enough. No way to get around the webpack integration
