### ISSUE TITLE
nativescript-material-cardview not work on android

### ISSUE THREAD

**Issue by robertototti** [Akylas/nativescript-material-components#44]
An uncaught Exception occurred on "main" thread.
Calling js method onCreateView failed
Error: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
    com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:240)
    com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:215)
    com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:143)
    com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:78)
    com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:121)
    com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:111)
    com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:107)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
    com.tns.Runtime.callJSMethod(Runtime.java:1109)
    com.tns.Runtime.callJSMethod(Runtime.java:1089)
    com.tns.Runtime.callJSMethod(Runtime.java:1081)
    com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
    androidx.fragment.app.Fragment.performCreateView(Fragment.java:2612)
    androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:874)
    androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
    androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
    androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
    androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2066)
    androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1856)
    androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
    androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
    androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
    android.os.Handler.handleCallback(Handler.java:873)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:193)
    android.app.ActivityThread.main(ActivityThread.java:6669)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

StackTrace:
	Frame: function:'push.../node_modules/nativescript-material-cardview/cardview.js.CardView.createNativeView', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 92540, column: 20
	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 138663, column: 31
	Frame: function:'', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 138705, column: 19
	Frame: function:'push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 147404, column: 26
	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 139950, column: 14
	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 138704, column: 14
	Frame: function:'', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 138705, column: 19
	Frame: function:'push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 147404, column: 26
	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 139950, column: 14
	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 138704, column: 14
	Frame: function:'', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 138705, column: 19
	Frame: function:'push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 147404, column: 26
	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 139950, column: 14
	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 138704, column: 14
	Frame: function:'', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 138705, column: 19
	Frame: function:'push.../node_modules/tns-core-modules/ui/content-view/content-view.js.ContentView.eachChildView', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 136470, column: 13
	Frame: function:'push.../node_modules/tns-core-modules/ui/page/page-common.js.PageBase.eachChildView', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 148497, column: 40
	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 139950, column: 14
	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 138704, column: 14
	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._addViewCore', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 138603, column: 18
	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._addView', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 138592, column: 14
	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 144507, column: 19
	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/fragment.js.FragmentClass.onCreateView', file:'file:///data/data/one.servolab.google.doc.beta/files/app/vendor.js', line: 142510, column: 38
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
	at com.tns.Runtime.callJSMethod(Runtime.java:1109)
	at com.tns.Runtime.callJSMethod(Runtime.java:1089)
	at com.tns.Runtime.callJSMethod(Runtime.java:1081)
	at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2612)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:874)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2066)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1856)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
	at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:240)
	at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:215)
	at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:143)
	at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:78)
	at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:121)
	at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:111)
	at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:107)
	... 24 more

**Comment by farfromrefug** [comment]
@robertototti It seems like you are using a custom android style.
Look at App_ressources/android/res/values/styles.xml
Ensure your themes inherit ```Theme.MaterialComponents```

**Comment by robertototti** [comment]
@farfromrefug can you help me. I do not understand what is wrong with my **styles.xml**
`
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:android="http://schemas.android.com/apk/res/android">

    
    <style name="LaunchScreenThemeBase" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="toolbarStyle">@style/NativeScriptToolbarStyle</item>

        <item name="colorPrimary">@color/ns_primary</item>
        <item name="colorPrimaryDark">@color/ns_primaryDark</item>
        <item name="colorAccent">@color/ns_accent</item>

        <item name="android:windowBackground">@drawable/splash_screen</item>
        
        <item name="android:windowActionBarOverlay">true</item>  
        <item name="android:windowTranslucentStatus">true</item>
    </style>

    <style name="LaunchScreenTheme" parent="LaunchScreenThemeBase">
    </style>

    
    <style name="AppThemeBase" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="toolbarStyle">@style/NativeScriptToolbarStyle</item>

        <item name="colorPrimary">@color/ns_primary</item>
        <item name="colorPrimaryDark">@color/ns_primaryDark</item>
        <item name="colorAccent">@color/ns_accent</item>
    </style>

    <style name="AppTheme" parent="AppThemeBase">
    </style>

    
    <style name="NativeScriptToolbarStyleBase" parent="Widget.AppCompat.Toolbar">
        <item name="android:background">@color/ns_primary</item>
        <item name="theme">@style/ThemeOverlay.AppCompat.ActionBar</item>
        <item name="popupTheme">@style/ThemeOverlay.AppCompat</item>
    </style>

    <style name="NativeScriptToolbarStyle" parent="NativeScriptToolbarStyleBase">
    </style>
</resources>
`

**Comment by farfromrefug** [comment]
simply replace all ```Theme.AppCompat.Light``` with ```Theme.MaterialComponents.Light```

**Comment by robertototti** [comment]
@farfromrefug Thanks!
