### ISSUE TITLE
nativescript-material-cardview does not support ng-content

### ISSUE THREAD

**Issue by robertototti** [Akylas/nativescript-material-components#45]
### this example will not work

`<MDCardView rippleColor="transparent" *ngIf="!isAndroid" class="w-full">`
`  <ng-content></ng-content>`
`</MDCardView>`

**Comment by farfromrefug** [comment]
I have no idea what it is supposed to do (ng-content). I dont use angular.
What s the error?

**Comment by robertototti** [comment]
@farfromrefug no error, but the content that was supposed to be instead of ***ng-content*** is also no

**Comment by farfromrefug** [comment]
No real idea. Might be a layout issue
What about this
```
<MDCardView rippleColor="transparent" *ngIf="!isAndroid" class="w-full">
<GridLayout>
<ng-content></ng-content>
</GridLayout>
</MDCardView>
```
