### ISSUE TITLE
[Android][iOS][SnackBar] Wrong snackbar displayed and crash

### ISSUE THREAD

**Issue by ADjenkov** [Akylas/nativescript-material-components#49]
__[Android] Issue 1__: `SnackBarOptions` doesn’t seem to work for android (backgroundColor, textColor) since in demo/snackbar colorful snackbar is not ‘colorful’

__[Android] Issue 2__: Demo application crashes on the 2nd ‘Simple Snackbar” dismiss with:

```
System.err: Calling js method onDismissed failed
System.err: TypeError: this.resolve is not a function
```
 
Steps to reproduce: 
1. Click on ‘Simple Snackbar” and wait for auto dismiss
2. Repeat 1. You can also reproduce it by manually dismissing

_Note1:I believe the problem is in src/snackbar/snackbar.android.ts -> onDismissed method implementation -> this.resolve = null;_
 
_Note2: I believe there is something wrong with this example page demo/snackbar. If I select ‘Action Snackbar’ then ‘Simple Snackbar’ and then ‘Action Snackbar’ again -> simple snackbar is shown instead of actionable one._

__[iOS] Issue 3__: Unable to show any snackbar after showing `Action Snackbar`. It looks like it's already dismissed but actually it’s not. If `Dismiss Snackbar` is used then the invisible snackbar can be shown again.

**Comment by farfromrefug** [comment]
@ADjenkov Thanks, found the issue. Will be fixed really soon

**Comment by farfromrefug** [comment]
@ADjenkov can you confirm it works now?
