### ISSUE TITLE
[BottomSheet] Demo app crash

### ISSUE THREAD

**Issue by ADjenkov** [Akylas/nativescript-material-components#50]
The demo/bottomSheet examples crash, since there is no such method `showBottomSheet` on View.

The problem might be related to the overriden version of View interface that should extend View with `showBottomSheet`"

```
declare module 'tns-core-modules/ui/core/view/view' {
   interface View {
       showBottomSheet(options: BottomSheetOptions): ViewBase;
       _setupAsRootView(context: any): void;
       callLoaded(): void;
       callUnloaded(): void;
       _removeFromFrameStack(): void;
   }
}
```

**Comment by farfromrefug** [comment]
@ADjenkov  what demo app are you talking about? The native one ? vue, ng?
You need to call "install" from ```nativescript-material-bottomsheet```... Don't like it but kind of need it.

**Comment by ADjenkov** [comment]
@farfromrefug I've tested with [this demo app](https://github.com/Akylas/nativescript-material-components/tree/master/demo). I believe all components are properly linked and installed to the demo app and then  `lerna run tsc` + `lerna run ngc` is executed. May be I need to install manually `nativescript-material-bottomsheet` inside the [demo](https://github.com/Akylas/nativescript-material-components/tree/master/demo) application?
