### ISSUE TITLE
Capture data, v-model not working

### ISSUE THREAD

**Issue by juanrdlo** [Akylas/nativescript-material-components#53]
Hello everyone, I have a problem, when running v-model in the MDTextField since when I try to write it indicates an error [object object] and is not capturing the data.

Can somebody help me?

`<MDTextField width="100%" v-model="id_passport" variant="outline" helper="" placeholderColor="white" keyboardType="number" hint="Ingrese su ID" returnKeyType="next" @focus="onFocus" @blur="onBlur" @textChange="onTextChange"/>

data(){
            return {
                id_passport: '',
            };
        },

`

![Screenshot_20190914-043812_educontrol](https://user-images.githubusercontent.com/48454427/64906259-cede4100-d6a9-11e9-8e72-9efb36350a4e.jpg)

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- iOS/Android versions 
- emulator or device. What type of device?

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by farfromrefug** [comment]
@juanrdlo it wont work without modifying your webpack config file. See that comment: https://github.com/Akylas/nativescript-material-components/issues/3#issuecomment-529649096

**Comment by juanrdlo** [comment]
the same error still appears. what you are indicating does not work

**Comment by farfromrefug** [comment]
Can you please attach the full error?

**Comment by juanrdlo** [comment]
I get the same error, when typing data in the input, it sends me the same image error

**Comment by farfromrefug** [comment]
@juanrdlo can you provide a fully working example?

**Comment by juanrdlo** [comment]
> @juanrdlo can you provide a fully working example?

I indicate that I get the same error that appears in the image when entering any value

**Comment by juanrdlo** [comment]
> @farfromrefug @juanrdlo can you provide a fully working example?

I indicate that I get the same error that appears in the image when entering any value

**Comment by farfromrefug** [comment]
@juanrdlo i am not asking what happens, i am asking for a full example so that i can reproduce and fix. BTW PRs are welcome ;)

**Comment by juanrdlo** [comment]
@farfromrefug  ok, can i add you to the repo? Or did I send you the apk?

**Comment by farfromrefug** [comment]
@juanrdlo  actually the best thing would be for you to create a new simple nativescript project which reproduce the issue. That way no other plug-ins and not too much code. It will beuch easier to fix
