### ISSUE TITLE
BottomSheet error with NG AOT

### ISSUE THREAD

**Issue by bradmartin** [Akylas/nativescript-material-components#55]
### Make sure to check the existing issues in this repository 
Similar to @shiv19 issue: https://github.com/Akylas/nativescript-material-components/issues/5 but this is within angular context.

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- Android only tested
- 6.1.0
- Pixel2 Android 10

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1
- Cross-platform modules: 6.1.1
- Runtime(s): 6.1.0
- Plugin(s): quite a few but seems to be isolated to this plugin since the demo app won't work with AOT either currently.

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
- I've added the module to app.module for bottomsheet.
- In app.component constructor tried adding `install` from the plugin `import { install } from 'nativescript-material-bottomsheet';` 
- I inject the service into the component trying to use it.
- execute:
```
  this._bottomSheet.show(ActivityComponent, options).subscribe(result => {
      console.log('Option selected:', result);
    });
```
Error when `show` is called.

```
JS: ERROR Error: Uncaught (in promise): Error: Failed to load page XML file for module: null
JS: Error: Failed to load page XML file for module: null
JS:     at Object.createViewFromEntry (file:///node_modules/tns-core-modules/ui/builder/builder.js:67:0) [angular]
JS:     at ProxyViewContainer.push.../node_modules/nativescript-material-bottomsheet/bottomsheet-common.js.ViewWithBottomSheetBase.showBottomSheet (file:///node_modules/nativescript-material-bottomsheet/bottomsheet-common.js:88:0) [angular]
JS:     at ProxyViewContainer.derivedCtor.<computed> [as showBottomSheet] (file:///node_modules/nativescript-material-core/core.common.js:41:0) [angular]
JS:     at file:///node_modules/nativescript-material-bottomsheet/angular/bottomsheet.service.js:34:0 [angular]
JS:     at Object.onInvoke (file:///node_modules/@angular/core/fesm5/core.js:26255:0) [angular]
JS:     at file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:883:0 [angular]
JS:     at Object.onInvokeTask (file:///data/data/com.permobil.pushtracker/files/app/vendor.js:35593:...
```

**Comment by bradmartin** [comment]
K - so what I've found so far:

- Do not use `install` with NG apps :)
- doesn't seem that `context` can be null in the `BottomSheetOptions` although it's declared optional in the interface.

Error when passing no `context` arg or `null` for context: 

```
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot set property 'closeCallback' of null
JS: TypeError: Cannot set property 'closeCallback' of null
JS:     at GridLayout.push.../node_modules/nativescript-material-bottomsheet/bottomsheet-common.js.ViewWithBottomSheetBase._showNativeBottomSheet (file:///node_modules/nativescript-material-bottomsheet/bottomsheet-common.js:56:0)
JS:     at GridLayout.push.../node_modules/nativescript-material-bottomsheet/bottomsheet.js.ViewWithBottomSheet._showNativeBottomSheet (file:///node_modules/nativescript-material-bottomsheet/bottomsheet.js:123:0)
JS:     at GridLayout.derivedCtor.<computed> [as _showNativeBottomSheet] (file:///node_modules/nativescript-material-core/core.common.js:41:0)
JS:     at ProxyViewContainer.push.../node_modules/nativescript-material-bottomsheet/bottomsheet-common.js.ViewWithBottomSheetBase.showBottomSheet (file:///node_modules/nativescript-material-bottomsheet/bottomsheet-common.js:91:0)
JS:     at file:///node_modules/nativescript-material-bottomsheet/angular/bottomsheet.service.js:34:0
JS:     at ZoneDelegat...
```

**Comment by henrychavez** [comment]
Hi @bradmartin, indeed for angular projects, the install method shouldn’t be called instead the module `NativeScriptMaterialBottomSheetModule.forRoot()` should be included in the main module, and that's it 😄 

Regarding passing `closeCallback` you shouldn’t do that when you use the `BottomSheetService` because is an observable so you can handle the actions using `.pipe(tap(result => {... do something}))` and the `context` can be undefined that's why is optional you shouldn’t have problems with that, maybe the problem was that you are sending the `closeCallback`.

**Comment by bradmartin** [comment]
I didn't have `closeCallback` defined tho. I just tried passing no context and it errored, with an empty context it worked 🤷‍♂  I didn't have time to try that on the demo app. It could be something project specific causing it if the demo works with null context.

**Comment by farfromrefug** [comment]
@bradmartin @henrychavez thanks for looking at it. Don't know s... about angular. Glad you can figure this out. Let me know if i can help.
