### ISSUE TITLE
Demo does not run --syncAllFiles option deprecated {N} CLI 6

### ISSUE THREAD

**Issue by chuckmitchell** [Akylas/nativescript-material-components#58]
### Make sure to check the demo app(s) for sample usage 
Did this, demo does not run.

### Make sure to check the existing issues in this repository 
Didn't see this issue mentioned.

### If the demo apps cannot help and there is no issue for your problem, tell us about it
The demo app does not run when following the instructions in Readme.md.
`
npm run demo.android

> nativescript-material-components@1.0.2 demo.android /Users/charles/projects/kanayo/mymobile-native-26/current/mymobile-native/nativescript-material-components
> cd ./demo && tns run android --syncAllFiles

{
The option 'syncAllFiles' is not supported.
Run 'tns run android --help' for more information.
`

### Which platform(s) does your issue occur on?
- Both
- All versions
- Emulator and device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.2

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

npm i
npm run tsc
npm run demo.ios
npm run demo.android

### Is there any code involved? 
The solution is simple, unless we want to support loading node_modules in {N} < 6 AND {N} >= 6

**Comment by farfromrefug** [comment]
Thanks! scripts have been updated

**Comment by chuckmitchell** [comment]
Thanks, closing 👍
