### ISSUE TITLE
Material TextField error inflating

### ISSUE THREAD

**Issue by ganeshbhat31055** [Akylas/nativescript-material-components#59]
### Which platform(s) does your issue occur on?
- Android 
-  Android Version 9
- emulator device

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) 
  6.1.0
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
  "version": "6.1.1"

- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
   "tns-android": {
      "version": "6.0.0"
    }

- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
   "dependencies": {
    "@vue/devtools": "^5.0.6",
    "nativescript-material-core": "^2.4.1",
    "nativescript-material-textfield": "^2.4.1",
    "nativescript-socketio": "^3.2.1",
    "nativescript-toasty": "^1.3.0",
    "nativescript-vue": "^2.4.0",
    "nativescript-vue-devtools": "^1.2.0",
    "tns-core-modules": "^6.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "nativescript-dev-webpack": "^1.0.0",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "vue-loader": "^15.4.0"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
   Tried to create  a textfield on a brand new app but there is an error inflating
    System.err: Error: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class com.google.android.material.textfield.TextInputLayout

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.
  XML File
    `<template>
     <Page xmlns:mdt="nativescript-material-textfield">
         <StackLayout horizontalAlignment="center">
             <MDTextField helper="example helper"
                         placeholderColor="green" keyboardType="datetime"
                         hint="i am an hint"/>
         </StackLayout>
     </Page>
  </template>`

  Main.js
   import TextFieldPlugin from 'nativescript-material-textfield/vue';

   Vue.use(TextFieldPlugin);

**Comment by ab192130** [comment]
Have you find a solution for this issue? I get same error :(

**Comment by farfromrefug** [comment]
Provide a complete logcat stacktrace please

**Comment by diegovincent** [comment]
#132
