### ISSUE TITLE
Persistent bottom-sheet

### ISSUE THREAD

**Issue by nik1st** [Akylas/nativescript-material-components#60]
I understand this plugin can build only modal bottom-sheet, not a persistent, that I want. I wish you will implement this feature in the future. 

Quote from https://material.io/components/sheets-bottom/#standard-bottom-sheet 

"Standard bottom sheets co-exist with the screen’s main UI region and allow for simultaneously viewing and interacting with both regions. They are commonly used to keep a feature or secondary content visible on screen when content in main UI region is frequently scrolled or panned."

Expected result: 

![Снимок экрана 2019-09-27 в 9 26 19](https://user-images.githubusercontent.com/37828793/65744267-eb966200-e108-11e9-8994-25d0d6490d93.png)

![Снимок экрана 2019-09-27 в 9 27 06](https://user-images.githubusercontent.com/37828793/65744308-08329a00-e109-11e9-9766-a738f6bdecd6.png)

**Comment by farfromrefug** [comment]
@NikStun  for now this is not part of native material-components. So it wont be added here.
However this is doable already.
I have implemented it in one of my app already in vue.
Don't really have the time to make a doc or even a component for it. But here is the code basically:
https://github.com/farfromrefug/alpimaps/tree/master/app/components/BottomSheet

**Comment by joshcomley** [comment]
I'm trying to achieve the same and have a basic implementation already just using `GridLayout`, and am looking into the code you posted.

But I'm curious why is this not something being considered for here?

**Comment by farfromrefug** [comment]
@joshcomley time ! ;) if i don't need i don't implement it. But PRs are welcome!
Though i would prefer a native implementation

**Comment by diegovincent** [comment]
Why close this @farfromrefug ? Could not we simply put a `HELP WANTED` label?

**Comment by farfromrefug** [comment]
@diegovincent No real point in keeping issues opened, makes it harder for me to maintain the project. You can continue the discussion here anyway. Then the next step is a PR.
