### ISSUE TITLE
White page with MDButton in ng

### ISSUE THREAD

**Issue by mchallenger88** [Akylas/nativescript-material-components#61]
When I add an MDButton to a page, the page comes up blank when navigating to it. 

This is an Nativescript/Angular project. All the latest updates to Nativescript have been made. 
NativeScriptMaterialButtonModule has been added to the imports section in the module.

**Comment by farfromrefug** [comment]
@mchallenger88 no example, no log, not much we can do ...

**Comment by mchallenger88** [comment]
I thought perhaps there was an easy answer. I'll create an example.

**Comment by mchallenger88** [comment]
I created a new ng project. Added the Material Button. On first build I get the following error:

System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class com.google.android.material.button.MaterialButton
System.err: Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class com.google.android.material.button.MaterialButton

**Comment by henrychavez** [comment]
You probably need to change your theme to use the material one, go to
App_Resources/ and take a look to the styles.xml file for an example. This
needs to be documented

**Comment by mchallenger88** [comment]
Thanks. I'll give it a try.

**Comment by mchallenger88** [comment]
Yes that's the problem. Thanks!
