### ISSUE TITLE
Feature: add support for IQKeyboardManager to BottomSheet

### ISSUE THREAD

**Issue by bradmartin** [Akylas/nativescript-material-components#62]
The recent changes to the bottomsheet on iOS to improve the empty top/bottom spacing between the NS layout and the bottom sheet added a small visual bug when IQKeyboardManager is used on a textfield shown in the bottomsheet. See image below:

IQKeyboard is open with the keyboard here:

![IMG_20190927_142015](https://user-images.githubusercontent.com/6006148/65796394-18ab3a80-e132-11e9-9dad-029ba78c187c.jpg)

IQKeyboardManager closed (keyboard dismissed):

![IMG_20190927_142020](https://user-images.githubusercontent.com/6006148/65796402-1b0d9480-e132-11e9-9cf7-7582772b23b7.jpg)

### Which platform(s) does your issue occur on?
- iOS
- any device with IQKeyboardManager installed for iOS apps.

### Please, provide the following version numbers that your issue occurs with:

- CLI:  6.1.2
- Cross-platform modules: 6.1.1
- Runtime(s): 6.1.1
- Plugin(s): latest bottom-sheet & iqkeyboardmanager

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
 - add IQKeyBoardManager to an iOS app, put a textfield in the bottom sheet and open it.

**Comment by bradmartin** [comment]
The IQKeyboardManager is a very popular NS plugin, so I imagine this might come up for other users who add textfields to bottomsheet layouts. I believe checking for `IQKeyboardManager` is sufficient.

So perhaps adding an additional padding to the top of the bottomsheet when the `IQKeyboardManager` is present in an app and opened. However, I've not looked at the API to determine if you can see if the keyboard is open and responding to events when it closes.

**Comment by farfromrefug** [comment]
@bradmartin might have time to take a look at this next week. Not sure though :s 
I think i know what the issue is. The rel issue is that the bottom sheet controller has a to constrain rule for the top safe area. 
The best solution for the other issue would be to disable that top safearea constraint but i did not manage to do it, so i cheated. THus that issue!
So the solution to this, which would not involve checking or ```IQKeyboardManager``` is to remove my cheat and disable that the top safearea constraint.

PS:  i expect the padding you are seeing to be even worse on iphone X

**Comment by jelledijkstra97** [comment]
Any news ont his? I'm experiencing the same problem

**Comment by stefanoScalzo** [comment]
@farfromrefug Can you give a code example of disabling the top safearea constraint ? I've tried it with iosOverflowSafeArea="true" and it still did not work? TIA

**Comment by farfromrefug** [comment]
@stefanoScalzo it should work as expected without doing anything. Was are you seeing, what s your code?

**Comment by stefanoScalzo** [comment]
> @stefanoScalzo it should work as expected without doing anything. Was are you seeing, what s your code?

`<ScrollView height="100%">
    <PreviousNextView #iqKeyboard  height="100%">
<GridLayout [marginTop]="keyboardActive?300:0" rows="auto,*" class="flex-vertical flex-vertical--black">
    <FlexboxLayout class="flex-vertical" row="0">
        <Label text="&#xf078;" class="fas close" (tap)="onClose($event)"></Label>
        <TextField
        (focus)="onFocus($event)"
        row="1"
        class="search fas"
        color="rgb(211, 211, 211)"
        style.placeholderColor="rgb(211, 211, 211)"
        hint="&#xf002; Search" 
        [text]="searchText"
        secure="false"
        returnKeyType="search" 
        autocorrect="false"
        (returnPress)="onFocus($event)"
        (textChange)="filterItems($event)">
        </TextField>
    </FlexboxLayout>

    <CollectionView
    row="1"
    height="800"
    rowHeight="50"
    colWidth="100%"
    [items]="items">
        <ng-template let-item="item">
            <FlexboxLayout class="flex-horizontal" (tap)="goToProfile(item.email)">
                <img class="profile-image" stretch="aspectFit"[src]="'https://storage.googleapis.com/test-for-bucket/'+item.profileImage+'.'+item.profileImageFormat"/>
                <Label marginRight="30"  class="name" [text]="item.displayname"></Label>
            </FlexboxLayout>
        </ng-template>
    </CollectionView>
</GridLayout>
</PreviousNextView>
</ScrollView>`

i had to go the margin route but I had tried iosOverflowSafeArea="true"  and iosOverflowSafeArea="false"  on the scrollview and neither worked

**Comment by farfromrefug** [comment]
what are you seeing? what s the code to open the bottom sheet?

**Comment by stefanoScalzo** [comment]
> what are you seeing? what s the code to open the bottom sheet?

The bottom sheet opens but when using ios keyboard everything goes off there screen

**Comment by farfromrefug** [comment]
@stefanoScalzo OK I can't help with so less details. please create a new issue with a repro example (not angular please)

**Comment by farfromrefug** [comment]
@HamzaHusain can you try to (disable)[https://github.com/tjvantoll/nativescript-IQKeyboardManager/blob/e7d1486f2f7f4e12347e1c388d5cf57a24e67df7/demo/app/main-view-model.ts#L30] IQKeyboardManager  while the bottomsheet is visible?

**Comment by HamzaHusain** [comment]
@farfromrefug This also occurs for the regular ios native keyboard (when IQKeyboard is disabled)

**Comment by farfromrefug** [comment]
@HamzaHusain @stefanoScalzo @bradmartin @jelledijkstra97 i think i finally fixed this. The bottomsheet wont "move" with the keyboard anymore.
there is a new option `ignoreKeyboardHeight` to change that behavior
