### ISSUE TITLE
ng TextField doesn't work with Reactive Forms

### ISSUE THREAD

**Issue by mchallenger88** [Akylas/nativescript-material-components#66]
I attempted to use the MDTextField control in a reactive form tying the control to formControlName and received the following error:

"Error: No value accessor for form control with name: [control name]"

Since the documentation states that the control inherits from the TextField not sure why this would happen.

**Comment by henrychavez** [comment]
Hi @mchallenger88, are you importing the forms module from angular?

**Comment by mchallenger88** [comment]
Yes of course. A normal textfield on the same page works fine.

⁣Sent from BlueMail ​

**Comment by PabloPG** [comment]
How did you solve this problem?

**Comment by mchallenger88** [comment]
I built my own custom control that does most of what the material textfield does and all of what I need. I can share if you like.

**Comment by PabloPG** [comment]
> I built my own custom control that does most of what the material textfield does and all of what I need. I can share if you like.

Can you share?

**Comment by mchallenger88** [comment]
Yes. Let me add some documentation and I'll post.

**Comment by mchallenger88** [comment]
I've attached the control. I put it in a StackLayout because it displays better like below. I'm sure there's a way to make it format correctly without it but it's a minor inconvenience and I haven't had time to research it.

<StackLayout  width="400">
        <TextFieldMaterial hint="Login Name" formControlName="login" [required]="true" [setValidate]="submitted"></TextFieldMaterial>
</StackLayout>

[textfield_material.zip](https://github.com/Akylas/nativescript-material-components/files/3935041/textfield_material.zip)

**Comment by diegovincent** [comment]
I have the exact same issue. @mchallenger88 could you please share?

**Comment by diegovincent** [comment]
I will re-open the issue if this is not re-opened, just to track it
