### ISSUE TITLE
[Android] Is it possible to add drawables to components?

### ISSUE THREAD

**Issue by kryoware** [Akylas/nativescript-material-components#67]
Just wondering if it would be possible to use things like `android:drawableEnd` / `android:drawableStart` on the TextField and/or Button component.

Also, is it possible to use the default password visiblity toggle for the TextField?

**Comment by farfromrefug** [comment]
@kryoware i did not add them yet because it is not a cross-platform feature.
However you can always do it by accessing the ```nativeView``` and modify it

**Comment by kryoware** [comment]
@farfromrefug on my end, using vue refs to do this only results in getting undefined for the functions. I can only get `nativeView` from event data.

**Comment by farfromrefug** [comment]
@kryoware well that s not normal! Working just fine here. Maybe you are accessing your refs too soon?
You should post you issue in the ```nativescript-vue``` repo

**Comment by kryoware** [comment]
@farfromrefug solved the issue regarding `nativeView` by using `this.$refs.<ref_name>.nativeView.nativeView`
