### ISSUE TITLE
Show MDTextField error outline but no message

### ISSUE THREAD

**Issue by BlueHunter99** [Akylas/nativescript-material-components#68]
This is just a question.

I am trying to use the MDTextField error outline to indicate that a wrong username and/or password has been submitted. However I don't want to display any error message, since I will be handling that differently.

I am using NativeScript with Angular on the latest versions while using NativeScript Sidekick to build on an android device.

An example of my textfield:
```
<MDTextField
    [placeholderColor]="stylingService.getPrimary()"
    hint="Wachtwoord"
    [(ngModel)]="password"
    variant="outline"
    row="5"
    col="1"
    secure="true"
    [error]="wrongInput ? ' ' : ''"
  ></MDTextField>
```

`wrongInput` is set based on the result of an HTML request.

Right now it changes the state from normal to error, but as it wants to render the space it also changes the height of the textfield. Is it possible to change the state without showing an error message?

**Comment by kryoware** [comment]
@BlueHunter99 I also wanted to do something like this, and after trying a bunch of stuff I just settled with using a "hacky" way. I turn off errors and just swap the `placeholderColor` / `strokeColor` depending on the error

**Comment by BlueHunter99** [comment]
@kryoware I should've thought of that myself. I'll try it out tomorrow but I'm pretty sure it will work. Thanks!

**Comment by kryoware** [comment]
@BlueHunter99  Hey, i figured out another way to do this, its still a bit hacky but this is what my Android dev friend suggested.
```
if(platform.isAndroid) {
  <text field object>.nativeView.setError(<your message>)

  if(<text field object>.nativeView.getChildCount() == 2) {
    <text field object>.nativeView.getChildAt(1).setVisibility(android.view.View.GONE)
  }
}
```

What this does is same as the default behavior, you turn on errors on the TextField but hide it from the view (hence the `View.GONE` bit). You get the error underline plus the focus animation on the TextField but now you can add your own way to display the message.

Note: `<your message>` should not be a blank text. Also attached before and after. The one with the icon is the custom view I made to display the error.
![after](https://user-images.githubusercontent.com/41801670/66560094-427c4c80-eb89-11e9-9059-58546d2740c3.png)
![before](https://user-images.githubusercontent.com/41801670/66560095-4314e300-eb89-11e9-9339-8cbc6984bdd5.png)

**Comment by m4r4c00ch0** [comment]
@kryoware how did you set the trailing view using this plugin (the eye icon on the password field)?

Did you access the underlying native APIs to accomplish it?

**Comment by kryoware** [comment]
@m4r4c00ch0 I used native code on Android. I didn't try it on iOS yet and I don't know if it's supported.

I think this is what I used. https://developer.android.com/reference/com/google/android/material/textfield/TextInputLayout?hl=en#setEndIconMode(int)

**Comment by m4r4c00ch0** [comment]
> @m4r4c00ch0 I used native code on Android. I didn't try it on iOS yet and I don't know if it's supported.
> 
> I think this is what I used. https://developer.android.com/reference/com/google/android/material/textfield/TextInputLayout?hl=en#setEndIconMode(int)

I figured. Thank you! Just FYI, in iOS you can do it (using native code as well) setting the `trailingView` attribute. See links below for more information:

- [TextField on iOS](https://material.io/components/text-fields/ios)
  - [Related post on StackOverflow](https://stackoverflow.com/a/65078136/10391569)

@farfromrefug is this feature implemented/bridged with the {N} plugin?
