### ISSUE TITLE
Access class functions in Vue (BottomNavigationBar)

### ISSUE THREAD

**Issue by tschaefermedia** [Akylas/nativescript-material-components#69]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.2
- Plugin(s):
"dependencies": {
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-loading-indicator": "^1.0.0",
    "@nstudio/nativescript-pulltorefresh": "^1.0.1",
    "@proplugins/nativescript-drop-down": "^6.0.0",
    "@vue/devtools": "^5.1.1",
    "axios": "^0.19.0",
    "moment": "^2.24.0",
    "nativescript-fonticon": "^2.0.0",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-gif": "^4.0.2",
    "nativescript-localize": "^4.2.0",
    "nativescript-material-bottomnavigationbar": "^2.5.0",
    "nativescript-plugin-firebase": "^10.0.1",
    "nativescript-socketio": "^3.3.1",
    "nativescript-theme-core": "^1.0.6",
    "nativescript-toasty": "^1.4.0",
    "nativescript-ui-dataform": "^5.1.1",
    "nativescript-ui-listview": "^7.1.0",
    "nativescript-vue": "^2.0.0",
    "nativescript-vue-devtools": "^1.2.0",
    "net": "^1.0.2",
    "tns-core-modules": "~6.1.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/preset-env": "^7.6.2",
    "babel-loader": "^8.0.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "^1.2.1",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.1.0",
    "terser-webpack-plugin": "^1.1.0",
    "vue-loader": "^15.2.6",
    "webpack": "^4.41.0",
    "webpack-bundle-analyzer": "^3.5.2",
    "webpack-cli": "^3.3.9"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 
How do I can access the JS methods in Vue.JS (code example: https://stackoverflow.com/questions/58310717/nativescript-vue-access-class-functions). I can't find a way to set badges and select tabs programatically.

Regards
Tobias

**Comment by kryoware** [comment]
@tschaefermedia access `nativeView` like I did here: https://github.com/Akylas/nativescript-material-components/issues/67#issuecomment-540324044

**Comment by tschaefermedia** [comment]
@kryoware thanks.
