### ISSUE TITLE
BottomSheet crashes on App window resize (Android, nativescript-angular)

### ISSUE THREAD

**Issue by hamidbsd** [Akylas/nativescript-material-components#72]
Which platform(s) does your issue occur on?

Android 8.0+
What type of device? any

Please, provide the following version numbers that your issue occurs with:

CLI: 6.1.2
Cross-platform modules: 6.1.2
Runtime: tns-android 6.1.2
Plugin(s): Angular 8.2.11, nativescript-material-components 2.5.2

Please, tell us how to recreate the issue in as much detail as possible.

On newer versions of Android you can actually grap the corner of the running app and resize it. If that is done when the bottom sheet is open, the app will crash.

Is there any code involved?

This is how the crash log looks like:

> An uncaught Exception occurred on "main" thread.
> Unable to start activity ComponentInfo{app.name/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onStart failed
> TypeError: Cannot read property 'owner' of undefined
> 
> StackTrace:
> java.lang.RuntimeException: Unable to start activity ComponentInfo{app.name/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onStart failed
> TypeError: Cannot read property 'owner' of undefined
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2974)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
> 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4950)
>

**Comment by farfromrefug** [comment]
@hamidbsd How to reproduce that? I dont have that feature on my phone?

**Comment by hamidbsd** [comment]
@farfromrefug don't your phone model. But I am able to reproduce in on all of my Samsung devices running Android 8.1.0+
It might be a Samsung UI feature.

My note on the bug:
When the app window is being resized, Android tried to re-render the main view according to the new dimension scale and that causes the crash. So I think the easiest solution would be to auto-dismiss the bottomsheet when resizing happens and right before the re-render process starts.

**Comment by farfromrefug** [comment]
@hamidbsd i would prefer not to for now. Plus your bug might actually not be related to that module. I would need the full error log. It says ```Calling js method onStart failed``` but i dont have the fulle stack

**Comment by hamidbsd** [comment]
I just tried to recreate the bug and it doesn't exist anymore! In fact bottomsheet gets dismissed (as expected) when the app window is resized.
As of {N} 6.5 and nativescript-material-bottomsheet 3.2.7
