### ISSUE TITLE
dialogs.prompt with inputType: inputType.password doesn't return the text

### ISSUE THREAD

**Issue by demetrio812** [Akylas/nativescript-material-components#74]
Hello,
the following method:

    protected showHiddenMenu() {
        const options: /*PromptOptions & MDCAlertControlerOptions*/any = DialogUtils.getDefaultPromptDialogOptions({
            title: 'Enter password',
            defaultText: '',
            inputType: inputType.password,
            okButtonText: 'Ok',
            cancelButtonText: 'Cancel'
            // inputType: dialogs.inputType.password TODO test in version 5
        });

        const me = this;
        dialogs.prompt(options).then((result: PromptResult) => {
            console.log(JSON.stringify(result));
            if (result && result.result && result.text === Environment.config.engMenuPassword) {
                me.showHiddenMenuOptions();
            } else {
                this.hiddenMenuHitTimes = 0; // reset counter
            }
        });
    }

It works when I use the import:

    import * as dialogs from 'tns-core-modules/ui/dialogs';

It doesn't when I use material component:

    import * as dialogs from 'nativescript-material-dialogs';

The result is always undefined

Thanks,
Dem

**Comment by farfromrefug** [comment]
@demetrio812 which platform?

**Comment by farfromrefug** [comment]
I actually cant reproduce your issue both on iOS and Android. For me password works fine
