### ISSUE TITLE
BottomSheetPlugin Error: this.nativeView.showBottomSheet Is Not a Function

### ISSUE THREAD

**Issue by jadedigital** [Akylas/nativescript-material-components#80]
Trying to use BottomSheetPlugin in a vue app. I must be calling $showBottomSheet incorrectly, but I'm following the intructions for NativeScript + Vue in the readme.

### Which platform(s) does your issue occur on?
- Android. Not tested on iOS 

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.2
- Runtime(s): tns-android: 'rc'

### Please, tell us how to recreate the issue in as much detail as possible. 
Install BottomSheetPlugin like this:

    import` Vue from 'nativescript-vue';
    import BottomSheetPlugin from 'nativescript-material-bottomsheet/vue';
    
    Vue.use(BottomSheetPlugin);

And then in a .vue file:

    import MyComponent from 'MyComponent.vue';

    this.$showBottomSheet(MyComponent, {})

I get the following error:

    An uncaught Exception occurred on "main" thread.
    Calling js method onClick failed
    TypeError: this.nativeView.showBottomSheet is not a function

See playground example here:
https://play.nativescript.org/?template=play-vue&id=17nhIV&v=3

**Comment by farfromrefug** [comment]
@jadedigital I think you are missing the "install"
Run app at the very beginning of your app. Before creating any View.
```ts
import {install} from 'nativescript-material-bottomsheet';
install();
```

For now this is a necessary evil

**Comment by jadedigital** [comment]
Thanks.

Now I'm getting this error:

    TypeError: Cannot set property 'closeCallback' of undefined

**Comment by farfromrefug** [comment]
Please wiitb the error stack

**Comment by jadedigital** [comment]
This is the error output:

JS: [Vue warn]: Error in v-on handler: "TypeError: Cannot set property 'closeCallback' of undefined"
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onTouch failed
System.err: TypeError: Cannot set property 'closeCallback' of undefined
System.err:
System.err: StackTrace:
System.err: ViewWithBottomSheetBase._showNativeBottomSheet(file:///app\src\bottomsheet\bottomsheet-common.ts:91:8)
System.err:     at ViewWithBottomSheet._showNativeBottomSheet(file:///app\src\bottomsheet\bottomsheet.android.ts:162:36)
System.err:     at derivedCtor.<computed>(file:///app\src\core\core.common.ts:38:53)
System.err:     at ViewWithBottomSheetBase.showBottomSheet(file:///app\src\bottomsheet\bottomsheet-common.ts:123:17)
System.err:     at Vue.$showBottomSheet(file:///app\src\bottomsheet\vue\index.ts:29:28)
System.err:     at showWeekSheet(file:///app\components\Items.vue:533:0)
System.err:     at invokeWithErrorHandling(file:///node_modules\nativescript-vue\dist\index.js:3364:25)
System.err:     at invoker(file:///node_modules\nativescript-vue\dist\index.js:4030:13)
System.err:     at _executeCallback(file:///node_modules\tns-core-modules\ui\gestures\gestures.js:307:26)
System.err:     at TapAndDoubleTapGestureListenerImpl._handleSingleTap(file:///node_modules\tns-core-modules\ui\gestures\gestures.js:56:20)
System.err:     at TapAndDoubleTapGestureListenerImpl.onSingleTapUp(file:///node_modules\tns-core-modules\ui\gestures\gestures.js:25:17)
System.err:     at GesturesObserver.androidOnTouchEvent(file:///node_modules\tns-core-modules\ui\gestures\gestures.js:253:40)
System.err:     at (file:///node_modules\tns-core-modules\ui\core\view\view.js:270:24)
System.err:     at View.handleGestureTouch(file:///node_modules\tns-core-modules\ui\core\view\view.js:269:17)
System.err:     at TouchListenerImpl.onTouch(file:///node_modules\tns-core-modules\ui\core\view\view.js:39:18)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at java.lang.Object_vendor_105439_26_TouchListenerImpl.onTouch(Unknown Source:13)
System.err:     at android.view.View.dispatchTouchEvent(View.java:13480)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
System.err:     at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:697)
System.err:     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1879)
System.err:     at android.app.Activity.dispatchTouchEvent(Activity.java:3487)
System.err:     at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
System.err:     at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:655)
System.err:     at android.view.View.dispatchPointerEvent(View.java:13732)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6119)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5897)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5346)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5399)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5365)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5524)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5373)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5581)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5346)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5399)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5365)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5373)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5346)
System.err:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8408)
System.err:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8341)
System.err:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8294)
System.err:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8523)
System.err:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:198)
System.err:     at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
System.err:     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:187)
System.err:     at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8482)
System.err:     at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8550)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:761)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:690)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7037)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by jadedigital** [comment]
Is there any working playground examples of bottomsheet with nativescript vue that I can take a look at?

**Comment by farfromrefug** [comment]
@jadedigital No playground possible. This plugin uses native libs so it wont work with the playground.
Found the issue. Will fix and release

**Comment by farfromrefug** [comment]
@jadedigital i released a fix in a beta version 3.0.0. Can you test it? Be careful though it requires ```@nativescript```

**Comment by kryoware** [comment]
@farfromrefug using version 3.0.0, This is what I get when I try to show the bottomsheet

```An uncaught Exception occurred on "main" thread.
Calling js method onStart failed
TypeError: Cannot convert undefined or null to object

StackTrace:
addPropertiesFromObject(file:///data/data/org.nativescript.demo/files/app/vendor.js:4891:10)
	at fromObject(file:///data/data/org.nativescript.demo/files/app/vendor.js:4905:3)
	at shownCallback(file:///data/data/org.nativescript.demo/files/app/vendor.js:91656:45)
	at BottomSheetDialogFragmentImpl.onStart(file:///data/data/org.nativescript.demo/files/app/vendor.js:91572:12)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
	at com.tns.gen.com.google.android.material.bottomsheet.BottomSheetDialogFragment_vendor_91501_26_BottomSheetDialogFragmentImpl.onStart(BottomSheetDialogFragment_vendor_91501_26_BottomSheetDialogFragmentImpl.java:31)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2632)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:874)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:198)
	at android.app.ActivityThread.main(ActivityThread.java:6729)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

**Comment by ngunyimacharia** [comment]
This worked for me with v3.1.5.

**Comment by tartinesKiller** [comment]
For anyone using this plugin and sticking with NativeScript 6, when calling `this.$showBottomSheet`, be sure to provide a context, even an empty one:
```js
this.$showBottomSheet(MyComponent, {
	props: {
		myProp: this.message,
	},
	context: {},
});
```
