### ISSUE TITLE
NS-Vue child._bottomSheetClosed is undefined

### ISSUE THREAD

**Issue by JuanDeLeon** [Akylas/nativescript-material-components#81]
### Which platform(s) does your issue occur on?
- iOS
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.2
- Cross-platform modules: tns-core-modules 6.0.0
- Runtime(s): 6.1.1
- Plugin(s): 
"dependencies": {
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-floatingactionbutton": "^1.1.0",
    "axios": "^0.19.0",
    "moment": "^2.24.0",
    "nativescript-camera": "^4.5.0",
    "nativescript-cfalert-dialog": "^1.0.15",
    "nativescript-datetimepicker": "^1.2.1",
    "nativescript-facebook": "^4.2.0",
    "nativescript-fancyalert": "^3.0.9",
    "nativescript-fonticon": "^2.0.0",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-material-bottomsheet": "^2.5.4",
    "nativescript-shadowed-label": "^1.0.0",
    "nativescript-social-share": "^1.5.2",
    "nativescript-status-bar": "^1.2.0",
    "nativescript-theme-core": "^1.0.6",
    "nativescript-videoplayer": "^4.2.1",
    "nativescript-vue": "^2.4.0",
    "tns-core-modules": "^6.0.0",
    "vuex": "^3.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "nativescript-dev-webpack": "^1.0.0",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "vue-loader": "^15.4.0"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 
The bottom sheet opens fine when I click on my button, but when I click outside of the sheet to close it, it fails with the given error.
JavaScript error:
file:///node_modules/nativescript-material-bottomsheet/bottomsheet-common.js:29:12: JS ERROR TypeError: child._bottomSheetClosed is not a function. (In 'child._bottomSheetClosed()', 'child._bottomSheetClosed' is undefined)
NativeScript caught signal 11.

### Is there any code involved? 
I'm just passing the id of the button which opens the bottom sheet as a string.
The callback is there in the options, not sure why it says it's undefined.

`let objId = "button1";
  
this.$showBottomSheet(ConfirmarCorreo, {
          closeCallback: (objId) => {
                 console.log('bottom sheet closed');
           }
  });`

**Comment by farfromrefug** [comment]
Will look at this
