### ISSUE TITLE
Parent's Binding Context Not Working in Material Textfield

### ISSUE THREAD

**Issue by joeytitans** [Akylas/nativescript-material-components#82]
### Make sure to check the existing issues in this repository 

Yes, was unable to find any mention of this issue.

### Which platform(s) does your issue occur on?
- Android
- SDK 28
- Nexus 5X Emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.2.0
- Cross-platform modules: 6.2.0
- Runtime(s): 6.2.0
- Plugin(s): nativescript-material-textfield 2.5.4 ; nativescript-folding-list-view 1.2.0

### Please, tell us how to recreate the issue in as much detail as possible. 
I have a textfield within a FoldingListView.  When attempting to retrieve the parent's binding context for the 'tap' method, it does not work on android only.  However, the same piece of code works using the regular TextField component.

### Is there any code involved? 
Within a list view, the following piece of code appears where it does not reach that tap method at all:
`                              <mdt:TextField text="{{ itemName }}" variant="outline" hint="Item Name *" helper="(*) required" row="0" col="0" margin="4" editable="false" tap="{{ $parents['FoldingListView'].openRevenueItems }}"/>
`

However, the following piece of code successfully calls the tap method:

`                              <TextField text="{{ itemName }}" helper="(*) required" row="0" col="0" margin="4" editable="false" tap="{{ $parents['FoldingListView'].openRevenueItems }}"/>
`

**Comment by farfromrefug** [comment]
I dont think it has anything to do with that plugin. Does it work with a normal TextField?

**Comment by joeytitans** [comment]
It works with a normal textfield under the exact same conditions.  The only change I made was going to the material textfield that breaks this piece of functionality.  It is within both a Tab and a FoldingListView in case that helps at all or is throwing something off.

**Comment by farfromrefug** [comment]
OK must be an issue here. Can you create a simple example project?
