### ISSUE TITLE
nativescript material ripple not working on android 5.1.1

### ISSUE THREAD

**Issue by YouSour** [Akylas/nativescript-material-components#83]
hi , i got a problem with nativescript material ripple running on android version 5.1.1 but other version are working , any idea or solution ? {N} Vue

**Comment by farfromrefug** [comment]
What is you problem?
Please give details if you want to be helped

**Comment by YouSour** [comment]
package.json
`{
    "name": "restaurant-app",
    "version": "1.0.0",
    "description": "restaurant app",
    "author": "heng you sour",
    "license": "MIT",
    "nativescript": {
        "id": "org.nativescript.application",
        "tns-ios": {
            "version": "6.0.1"
        },
        "tns-android": {
            "version": "6.0.2"
        }
    },
    "dependencies": {
        "axios": "^0.19.0",
        "lodash": "^4.17.11",
        "moment": "^2.24.0",
        "nativescript-cardview": "^3.2.0",
        "nativescript-fancyalert": "^3.0.9",
        "nativescript-localstorage": "^2.0.0",
        "nativescript-material-ripple": "^2.3.17",
        "nativescript-theme-core": "^1.0.6",
        "nativescript-ui-listview": "^7.0.1",
        "nativescript-vue": "^2.0.0",
        "numeral": "^2.0.6",
        "tns-core-modules": "6.0.1",
        "vuex": "^3.0.1"
    },
    "devDependencies": {
        "@babel/core": "^7.0.0",
        "@babel/preset-env": "^7.0.0",
        "babel-loader": "^8.0.2",
        "babel-traverse": "6.26.0",
        "babel-types": "6.26.0",
        "babylon": "6.18.0",
        "clean-webpack-plugin": "^0.1.19",
        "copy-webpack-plugin": "^4.5.2",
        "css-loader": "^1.0.0",
        "lazy": "1.0.11",
        "nativescript-dev-webpack": "1.0.1",
        "nativescript-vue-template-compiler": "^2.0.0",
        "nativescript-worker-loader": "^0.9.6-next-2019-07-16-195451-01",
        "node-sass": "^4.9.2",
        "sass-loader": "^7.1.0",
        "terser-webpack-plugin": "^1.1.0",
        "vue-loader": "^15.2.6",
        "webpack": "^4.16.4",
        "webpack-bundle-analyzer": "~2.13.1",
        "webpack-cli": "^3.1.0"
    }
}
`
at the moment i'm working on {N} vue , it makes my app crush . i test it on android version 7 > 5.1.1 it doesn't works but from version 7.1.1 > it works perfectly .

**Comment by farfromrefug** [comment]
@YouSour ok. As it crashes you must have a crash log. Please post the crash log. Also could you please could you create a simple project to recreate the issue?

**Comment by YouSour** [comment]
here , a crush log : 
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: java.lang.NoSuchMethodError: no non-static method "Landroid/view/View;.setForeground(Landroid/graphics/drawable/Drawable;)V"
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err:     androidx.fragment.app.Fragment.performCreateView(Fragment.java:2612)
System.err:     androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:874)
System.err:     androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
System.err:     androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
System.err:     androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
System.err:     androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2066)
System.err:     androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1856)
System.err:     androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
System.err:     androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
System.err:     androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
System.err:     android.os.Handler.handleCallback(Handler.java:739)
System.err:     android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     android.os.Looper.loop(Looper.java:135)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5254)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:372)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
System.err: StackTrace:
System.err: 	Frame: function:'Ripple.setRippleDrawable', file:'file:///app/src/ripple/ripple.android.ts:222:17
System.err: 	Frame: function:'Ripple.createNativeView', file:'file:///app/src/ripple/ripple.android.ts:209:13
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:491:30
System.err: 	Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:533:18
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:25
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///node_modules/tns-core-modules/ui/core/view/view-common.js:992:13
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:532:13
System.err: 	Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:533:18
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:25
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///node_modules/tns-core-modules/ui/core/view/view-common.js:992:13
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:532:13
System.err: 	Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:533:18
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:25
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///node_modules/tns-core-modules/ui/core/view/view-common.js:992:13
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:532:13
System.err: 	Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:533:18
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:25
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///node_modules/tns-core-modules/ui/core/view/view-common.js:992:13
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:532:13
System.err: 	Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:533:18
System.err: 	Frame: function:'ContentView.eachChildView', file:'file:///node_modules/tns-core-modules/ui/content-view/content-view.js:70:12
System.err: 	Frame: function:'PageBase.eachChildView', file:'file:///node_modules/tns-core-modules/ui/page/page-common.js:126:39
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///node_modules/tns-core-modules/ui/core/view/view-common.js:992:13
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:532:13
System.err: 	Frame: function:'ViewBase._addViewCore', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:431:17
System.err: 	Frame: function:'ViewBase._addView', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:420:13
System.err: 	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///node_modules/tns-core-modules/ui/frame/frame.js:684:18
System.err: 	Frame: function:'FragmentClass.onCreateView', file:'file:///node_modules/tns-core-modules/ui/frame/fragment.js:26:37
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err: 	at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err: 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2612)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:874)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
System.err: 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2066)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1856)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
System.err: 	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:135)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5254)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
System.err: Caused by: java.lang.NoSuchMethodError: no non-static method "Landroid/view/View;.setForeground(Landroid/graphics/drawable/Drawable;)V"
System.err: 	... 25 more

**Comment by YouSour** [comment]
here , a crush log : 
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: java.lang.NoSuchMethodError: no non-static method "Landroid/view/View;.setForeground(Landroid/graphics/drawable/Drawable;)V"
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err:     androidx.fragment.app.Fragment.performCreateView(Fragment.java:2612)
System.err:     androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:874)
System.err:     androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
System.err:     androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
System.err:     androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
System.err:     androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2066)
System.err:     androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1856)
System.err:     androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
System.err:     androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
System.err:     androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
System.err:     android.os.Handler.handleCallback(Handler.java:739)
System.err:     android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     android.os.Looper.loop(Looper.java:135)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5254)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:372)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
System.err: StackTrace:
System.err: 	Frame: function:'Ripple.setRippleDrawable', file:'file:///app/src/ripple/ripple.android.ts:222:17
System.err: 	Frame: function:'Ripple.createNativeView', file:'file:///app/src/ripple/ripple.android.ts:209:13
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:491:30
System.err: 	Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:533:18
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:25
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///node_modules/tns-core-modules/ui/core/view/view-common.js:992:13
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:532:13
System.err: 	Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:533:18
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:25
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///node_modules/tns-core-modules/ui/core/view/view-common.js:992:13
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:532:13
System.err: 	Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:533:18
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:25
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///node_modules/tns-core-modules/ui/core/view/view-common.js:992:13
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:532:13
System.err: 	Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:533:18
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:25
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///node_modules/tns-core-modules/ui/core/view/view-common.js:992:13
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:532:13
System.err: 	Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:533:18
System.err: 	Frame: function:'ContentView.eachChildView', file:'file:///node_modules/tns-core-modules/ui/content-view/content-view.js:70:12
System.err: 	Frame: function:'PageBase.eachChildView', file:'file:///node_modules/tns-core-modules/ui/page/page-common.js:126:39
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///node_modules/tns-core-modules/ui/core/view/view-common.js:992:13
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:532:13
System.err: 	Frame: function:'ViewBase._addViewCore', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:431:17
System.err: 	Frame: function:'ViewBase._addView', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:420:13
System.err: 	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///node_modules/tns-core-modules/ui/frame/frame.js:684:18
System.err: 	Frame: function:'FragmentClass.onCreateView', file:'file:///node_modules/tns-core-modules/ui/frame/fragment.js:26:37
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err: 	at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err: 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2612)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:874)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
System.err: 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2066)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1856)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
System.err: 	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:135)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5254)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
System.err: Caused by: java.lang.NoSuchMethodError: no non-static method "Landroid/view/View;.setForeground(Landroid/graphics/drawable/Drawable;)V"
System.err: 	... 25 more
and here a test project : [https://github.com/YouSour/ripple]()

**Comment by farfromrefug** [comment]
@YouSour awesome! I see the issue. Will fix it

**Comment by KEYHAN-A** [comment]
Android still not working, any fixes yet?

**Comment by farfromrefug** [comment]
@KEYHAN-A may be a report with versions and logs? Better than asking like "any fixes yet"... ;)
THanks

**Comment by KEYHAN-A** [comment]
@farfromrefug 
```
...
    "nativescript-material-ripple": "^2.5.4",
    "nativescript-vue": "~2.4.0",
    "tns-core-modules": "~6.2.0",
...
```
these are the versions I use, and the thing is I don't get any errors or logs,
it just doesn't do anything on Android, but it works in iOS.

**Comment by farfromrefug** [comment]
@KEYHAN-A ok so nothing to do with that issue right? And you don't even give me info about the android version... I would guess you are on a old version of android where RippleDrawable is [not supported](https://developer.android.com/reference/android/graphics/drawable/RippleDrawable)

@YouSour i will close this issue due to inactivity. Let me know if you still see the issue with latest beta

**Comment by KEYHAN-A** [comment]
<img width="907" alt="Screen Shot 2019-12-09 at 11 36 14 AM" src="https://user-images.githubusercontent.com/6815523/70420158-1ccfce80-1a78-11ea-9c62-96f90222c920.png">

this is my emulator, using the latest Android.
I also tried on my phone with Android 9 right now,
nothing happens on android

**Comment by farfromrefug** [comment]
@KEYHAN-A Again if you think this is an issue. PLease send logs, all versions and a sample code to reproduce.

**Comment by KEYHAN-A** [comment]
@farfromrefug I just created a new blank Nativescript-Vue project with latest versions of everything,
added ripple plugin and create a simple rectangle,
ripple effect works on ios but not Android, and no errors or logs

**Comment by farfromrefug** [comment]
@KEYHAN-A I am sorry to tell you that really, but i am not there to "decipher" what you are saying and i am maintaining that on my free time. If you are not able to share fully reproducible samples with logs and everything necessary to quickly reproduce the issue, i won't be able to help you.
I will stop discussing this here. Hope you understand

**Comment by KEYHAN-A** [comment]
@farfromrefug hey man, I understand it, really,
but you're just a `tns create project` away with the issue.
just a blank project with ripple plugin on it, 
doesn't work on android, that's it,
there's no logs, errors or anything else I can share,
I'm using the latest versions of everything,
and I'm testing with Android 10 on emulator and Android 9 on my phone,
this is my package.json
```
{
  "nativescript": {
    "id": "org.nativescript.rippletest",
    "tns-android": {
      "version": "6.2.0"
    },
    "tns-ios": {
      "version": "6.2.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@nativescript/theme": "~2.2.0",
    "nativescript-material-ripple": "^2.5.4",
    "nativescript-vue": "~2.4.0",
    "tns-core-modules": "~6.2.0"
  },
  "devDependencies": {
    "@babel/core": "~7.1.0",
    "@babel/preset-env": "~7.1.0",
    "babel-loader": "~8.0.0",
    "nativescript-dev-webpack": "~1.3.0",
    "nativescript-vue-template-compiler": "~2.4.0",
    "node-sass": "^4.7.1",
    "vue-loader": "~15.4.0"
  },
  "gitHead": "",
  "readme": "NativeScript Application"
}

```

this is my app.js
```
import Vue from "nativescript-vue";
import Home from "./components/Home";
import RipplePlugin from 'nativescript-material-ripple/vue';
Vue.use(RipplePlugin);
new Vue({
    template: `
        <Frame>
            <Home />
        </Frame>`,
    components: {
        Home
    }
}).$start();

```

and my Home.vue
```
<template>
    <Page>
        <ActionBar />
        <GridLayout>
            <StackLayout>
                <MDRipple rippleColor="green" width="100%" height="100" backgroundColor="#ccc" />
            </StackLayout>
        </GridLayout>
    </Page>
</template>

<script>
export default {
}
</script>
```

just a blank project
