### ISSUE TITLE
Dialog Background Color

### ISSUE THREAD

**Issue by DonsWayo** [Akylas/nativescript-material-components#85]
Is posible in some way to change the Dialog background color? by css or when create? I don't see any option for that.

**Comment by farfromrefug** [comment]
@DonsWayo here is an example:
https://github.com/Akylas/nativescript-material-components/blob/master/demo-vue/app/examples/Dialogs.vue#L109

**Comment by farfromrefug** [comment]
@DonsWayo is it good? can you close the issue?

**Comment by DonsWayo** [comment]
yes sorry for the delay, is okay :)
