### ISSUE TITLE
problem navigation with BottomNavigation element of Nativescript and material design

### ISSUE THREAD

**Issue by fvdung** [Akylas/nativescript-material-components#87]
### Which platform(s) does your issue occur on?
- iOS/Android/Both:  Android
- iOS/Android versions: Every versions
- emulator or device. What type of device? Both

### Please, provide the following version numbers that your issue occurs with:
Please view project demo
[https://github.com/fvdung/bug-bottomNavigation-Nativescript-with-material-design](https://github.com/fvdung/bug-bottomNavigation-Nativescript-with-material-design)

### Please, tell us how to recreate the issue in as much detail as possible. 
`tns run android`

As you can see, I can navigate from page 2 to page 1, but when navigating from page 1 to the homepage, an exception is raised.
This does not happen in version 2.5.2 of this plugin
I think there was something wrong with the BottomNavigation element of Nativescript

**Comment by farfromrefug** [comment]
@fvdung this does not seem to be an error with this plugin. 
First this does not happen when switching tabs , but when going into details then back.
I think it has to do with the frame and fragments.

I will close this here for now and let you report this in {N}. Also keep in mind that by using the latest version for this plugin you are now using the latest versions of androidX!
