### ISSUE TITLE
Textfield expands when cursor is placed inside field

### ISSUE THREAD

**Issue by matty0005** [Akylas/nativescript-material-components#90]
Hi, I am trying to increase the font size used in the text fields, but when I do so, the font size adjusts, but the size of the text field remains the same and expands when the cursor clicks inside the field. I am using an IOS emulator.

I have changed the font size by using the following css property: `font-size: 30;`

Here is some screenshots of this issue: [https://imgur.com/a/qe7YqSX](https://imgur.com/a/qe7YqSX)

How can I set the height of the textfield so the text box does not expand upon clicking in the field?

**Comment by farfromrefug** [comment]
It does not happen if you dont change the font size?
Can you share a simple sample to reproduce the issue?
