### ISSUE TITLE
TextField returnKeyType

### ISSUE THREAD

**Issue by PabloPG** [Akylas/nativescript-material-components#92]
How can i force the focus and keyboard view?

### Which platform(s) does your issue occur on?
**- iOS/Android/Both:** Android
**- iOS/Android versions:** Android 7
**- emulator or device. What type of device?:** Device and Emulator

### Please, provide the following version numbers that your issue occurs with:

**- CLI:** 6.2.2
**- Cross-platform modules:** 6.2.3
**- Runtime(s):** 6.2.0
**- Plugin(s):** 2.5.4

### Please, tell us how to recreate the issue in as much detail as possible. 
Create two or more Text Field with method `returnKeyType="next"`. When the key "next" is pressed, the textfield dont receive focus and dont show the keyboard

### Is there any code involved? 
```
<GridLayout rows="auto, auto, auto, auto" [formGroup]="loginFormGroup" class="form-group">
	<MDTextField #link hint="Link" variant="outline" formControlName="Link" autocorrect="false" keyboardType="email" (blur)=" returnKeyType="next" autocapitalizationType="none" class="m-t-10">
	</MDTextField>
	
	<MDTextField #login row="1" hint="User" variant="outline" formControlName="Login" autocorrect="false" keyboardType="email" returnKeyType="next" autocapitalizationType="none" class="m-t-10">
	</MDTextField>
	
	<StackLayout row="2">
		<MDTextField #pw hint="Password" variant="outline" formControlName="Password" autocorrect="false" keyboardType="email" returnKeyType="next" autocapitalizationType="none" secure="true" class="m-t-10">
		</MDTextField>
		<Label text="Forgot the password?" class="helper-link"></Label>
	</StackLayout>
	
	<Button row="3" text="Confirm" (tap)="submit()" [isEnabled]="!loginFormGroup.invalid" class="btn btn-primary m-t-20"></Button>
</GridLayout>
```

**Comment by farfromrefug** [comment]
First thanks for the description. Now this is not a bug but a platform feature.
You ll have to handle that in your app.
Sorry

**Comment by kanayo** [comment]
Just the help out the OP: Looks like you are missing the (returnPress) part:

link field:
returnKeyType="next" (returnPress)="login.requestFocus()"

login field:
returnKeyType="next" (returnPress)="pw.requestFocus()"

pw field:
returnKeyType="done" (returnPress)="submit()"

**Comment by PabloPG** [comment]
> Just to help out the OP: Looks like you are missing the (returnPress) part:
> 
> link field:
> returnKeyType="next" (returnPress)="login.requestFocus()"
> 
> login field:
> returnKeyType="next" (returnPress)="pw.requestFocus()"
> 
> pw field:
> returnKeyType="done" (returnPress)="submit()"

Very thanks
