### ISSUE TITLE
BottomSheet - Event for clossing by background click or moving to close

### ISSUE THREAD

**Issue by PabloPG** [Akylas/nativescript-material-components#94]
### If the demo apps cannot help and there is no issue for your problem, tell us about it

I think this is a feature.
Create a event where when 'BottomSheet' has to closed by background click or moving to bottom to close, calls this.

Exemple: When my bottomsheet has a checkbox, return the selecteds.
if exists, please disconsider and how i get the event?

### Which platform(s) does your issue occur on?
**- iOS/Android/Both** Android
**- iOS/Android versions** 7
**- emulator or device. What type of device?** Emulator and Device

### Please, provide the following version numbers that your issue occurs with:

**- CLI:** 6.2.2
**- Cross-platform modules:** 6.2.3
**- Runtime(s):** 6.2.0
**- Plugin(s):** 2.5.4

**Comment by farfromrefug** [comment]
@PabloPG not sure i understand what you want. You want an event to be fired when the bottomsheet is closed?
