### ISSUE TITLE
[IOS] Custom Dialogs not working with {N} 6.3.2

### ISSUE THREAD

**Issue by fvdung** [Akylas/nativescript-material-components#95]
### Which platform(s) does your issue occur on?
- platform: iOS 
- iOS versions: every versions
- emulator or device. Both

### Please, provide the following version numbers that your issue occurs with:
- CLI: 6.3.0
- Cross-platform modules: 
     + @nativescript/core 6.3.2
     + nativescript-vue 2.5.0-alpha.3
- Runtime(s): tns-ios 6.3.0
- Plugin(s): 
     + nativescript-material-core 3.0.6
     + nativescript-material-textfield 3.0.6
     + nativescript-material-dialogs 3.0.6

### Please, tell us how to recreate the issue in as much detail as possible. 
The screen freezes when I show dialogs, without the error being displayed in the terminal

### Is there any code involved? 
Code from demo-vue

```
                const stack = new StackLayout();
                stack.orientation = 'horizontal';
                stack.verticalAlignment = 'middle';
                // stack.height = {value:100, unit:'dip'};
                stack.padding = 24;
                // stack.margin = 30;
                stack.backgroundColor = 'red';
                const activityIndicator = new ActivityIndicator();
                activityIndicator.className = 'activity-indicator';
                activityIndicator.backgroundColor = 'yellow';
                activityIndicator.busy = true;
                activityIndicator.verticalAlignment = 'middle';
                stack.addChild(activityIndicator);
                const label = new Label();
                label.verticalAlignment = 'middle';
                label.backgroundColor = 'brown';
                label.text = 'test';
                stack.addChild(label);

                const dialog = new AlertDialog({
                    title: 'tsst',
                    message: null,
                    view: stack
                });
                dialog.show();
```

**Comment by farfromrefug** [comment]
I have seen that. No solution yet or even soon. I have a lot of things to work on first. I guess it comes from the bump in the pod file versions

**Comment by farfromrefug** [comment]
@fvdung it should be fixed in 3.0.9. Can you confirm?

**Comment by fvdung** [comment]
I removed the plugin dialogs in my project to fully use the bottomsheet. However, I can confirm that the plugin dialogs are working again

**Comment by farfromrefug** [comment]
thanks can you close that issue please?
